///|
test "2546.smt2" {
  let source = @fs.read_file_to_string("./smt2/2546.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.27.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.27.smt2")
  ignore(parse_smtlib(source))
}

///|
test "mut_rec4sdk_output1.smt2" {
  let source = @fs.read_file_to_string("./smt2/mut_rec4sdk_output1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3670.smt2" {
  let source = @fs.read_file_to_string("./smt2/3670.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4000.smt2" {
  let source = @fs.read_file_to_string("./smt2/4000.smt2")
  ignore(parse_smtlib(source))
}

///|
test "intervalUpDivide.smt2" {
  let source = @fs.read_file_to_string("./smt2/intervalUpDivide.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-17.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-17.smt2")
  ignore(parse_smtlib(source))
}

///|
test "error.smt2" {
  let source = @fs.read_file_to_string("./smt2/error.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3101.smt2" {
  let source = @fs.read_file_to_string("./smt2/3101.smt2")
  ignore(parse_smtlib(source))
}

///|
test "rec.smt2" {
  let source = @fs.read_file_to_string("./smt2/rec.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3858.smt2" {
  let source = @fs.read_file_to_string("./smt2/3858.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3730.smt2" {
  let source = @fs.read_file_to_string("./smt2/3730.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl33.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl33.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string7.smt2" {
  let source = @fs.read_file_to_string("./smt2/string7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3589.smt2" {
  let source = @fs.read_file_to_string("./smt2/3589.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-datatype_with_float-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-datatype_with_float-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-13.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3420.smt2" {
  let source = @fs.read_file_to_string("./smt2/3420.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4020.smt2" {
  let source = @fs.read_file_to_string("./smt2/4020.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6582.smt2" {
  let source = @fs.read_file_to_string("./smt2/6582.smt2")
  ignore(parse_smtlib(source))
}

///|
test "dejan_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/dejan_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1841.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1841.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.25.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.25.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t155.smt2" {
  let source = @fs.read_file_to_string("./smt2/t155.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl53.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl53.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t144.smt2" {
  let source = @fs.read_file_to_string("./smt2/t144.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl6.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2343.smt2" {
  let source = @fs.read_file_to_string("./smt2/2343.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3215.smt2" {
  let source = @fs.read_file_to_string("./smt2/3215.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3238.smt2" {
  let source = @fs.read_file_to_string("./smt2/3238.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3402.smt2" {
  let source = @fs.read_file_to_string("./smt2/3402.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-datatype_with_float-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-datatype_with_float-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1665.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1665.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2956.smt2" {
  let source = @fs.read_file_to_string("./smt2/2956.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3695.smt2" {
  let source = @fs.read_file_to_string("./smt2/3695.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-17.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-17.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3645.smt2" {
  let source = @fs.read_file_to_string("./smt2/3645.smt2")
  ignore(parse_smtlib(source))
}

///|
test "pat1.smt2" {
  let source = @fs.read_file_to_string("./smt2/pat1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "consequence_fd.smt2" {
  let source = @fs.read_file_to_string("./smt2/consequence_fd.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t183.smt2" {
  let source = @fs.read_file_to_string("./smt2/t183.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_float-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_float-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "strategy-par-or-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/strategy-par-or-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3120.smt2" {
  let source = @fs.read_file_to_string("./smt2/3120.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3158.smt2" {
  let source = @fs.read_file_to_string("./smt2/3158.smt2")
  ignore(parse_smtlib(source))
}

///|
test "chain.smt2" {
  let source = @fs.read_file_to_string("./smt2/chain.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3911.smt2" {
  let source = @fs.read_file_to_string("./smt2/3911.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl8.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-eq-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-eq-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6593.smt2" {
  let source = @fs.read_file_to_string("./smt2/6593.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3953.smt2" {
  let source = @fs.read_file_to_string("./smt2/3953.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2852.smt2" {
  let source = @fs.read_file_to_string("./smt2/2852.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t113.smt2" {
  let source = @fs.read_file_to_string("./smt2/t113.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t137.smt2" {
  let source = @fs.read_file_to_string("./smt2/t137.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3811.smt2" {
  let source = @fs.read_file_to_string("./smt2/3811.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1366.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1366.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-37.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-37.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5911.smt2" {
  let source = @fs.read_file_to_string("./smt2/5911.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-19.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-19.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine3.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3910.smt2" {
  let source = @fs.read_file_to_string("./smt2/3910.smt2")
  ignore(parse_smtlib(source))
}

///|
test "purify_arith.smt2" {
  let source = @fs.read_file_to_string("./smt2/purify_arith.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3715.smt2" {
  let source = @fs.read_file_to_string("./smt2/3715.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4018.smt2" {
  let source = @fs.read_file_to_string("./smt2/4018.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-12.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "trig-intersection.smt2" {
  let source = @fs.read_file_to_string("./smt2/trig-intersection.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t121.smt2" {
  let source = @fs.read_file_to_string("./smt2/t121.smt2")
  ignore(parse_smtlib(source))
}

///|
test "core.smt2" {
  let source = @fs.read_file_to_string("./smt2/core.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3042.smt2" {
  let source = @fs.read_file_to_string("./smt2/3042.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-12.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t198.smt2" {
  let source = @fs.read_file_to_string("./smt2/t198.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3865.smt2" {
  let source = @fs.read_file_to_string("./smt2/3865.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-30.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-30.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1645.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1645.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3327.smt2" {
  let source = @fs.read_file_to_string("./smt2/3327.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "arith_bug3.smt2" {
  let source = @fs.read_file_to_string("./smt2/arith_bug3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "dt_ayrat_2.smt2" {
  let source = @fs.read_file_to_string("./smt2/dt_ayrat_2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-add-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-add-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-13.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3319.smt2" {
  let source = @fs.read_file_to_string("./smt2/3319.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3574.smt2" {
  let source = @fs.read_file_to_string("./smt2/3574.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3518.smt2" {
  let source = @fs.read_file_to_string("./smt2/3518.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2566.smt2" {
  let source = @fs.read_file_to_string("./smt2/2566.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-13.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3246.smt2" {
  let source = @fs.read_file_to_string("./smt2/3246.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-tests-double-non-partial.smt2" {
  let source = @fs.read_file_to_string(
    "./smt2/fp-rem-tests-double-non-partial.smt2",
  )
  ignore(parse_smtlib(source))
}

///|
test "3644.smt2" {
  let source = @fs.read_file_to_string("./smt2/3644.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3550.smt2" {
  let source = @fs.read_file_to_string("./smt2/3550.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3842.smt2" {
  let source = @fs.read_file_to_string("./smt2/3842.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl52.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl52.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t136.smt2" {
  let source = @fs.read_file_to_string("./smt2/t136.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2921.smt2" {
  let source = @fs.read_file_to_string("./smt2/2921.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3548.smt2" {
  let source = @fs.read_file_to_string("./smt2/3548.smt2")
  ignore(parse_smtlib(source))
}

///|
test "pat3.smt2" {
  let source = @fs.read_file_to_string("./smt2/pat3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl23.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl23.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t200.smt2" {
  let source = @fs.read_file_to_string("./smt2/t200.smt2")
  ignore(parse_smtlib(source))
}

///|
test "strategy-par-or-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/strategy-par-or-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-15.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl46.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl46.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-22.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-22.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-28.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-28.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3728.smt2" {
  let source = @fs.read_file_to_string("./smt2/3728.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2456.smt2" {
  let source = @fs.read_file_to_string("./smt2/2456.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2938.smt2" {
  let source = @fs.read_file_to_string("./smt2/2938.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3103.smt2" {
  let source = @fs.read_file_to_string("./smt2/3103.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3029.smt2" {
  let source = @fs.read_file_to_string("./smt2/3029.smt2")
  ignore(parse_smtlib(source))
}

///|
test "with.smt2" {
  let source = @fs.read_file_to_string("./smt2/with.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2908.smt2" {
  let source = @fs.read_file_to_string("./smt2/2908.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6319.smt2" {
  let source = @fs.read_file_to_string("./smt2/6319.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-3225.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-3225.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3116.smt2" {
  let source = @fs.read_file_to_string("./smt2/3116.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2450.smt2" {
  let source = @fs.read_file_to_string("./smt2/2450.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t101.smt2" {
  let source = @fs.read_file_to_string("./smt2/t101.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl11.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o2.smt2" {
  let source = @fs.read_file_to_string("./smt2/o2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1655.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1655.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t219.smt2" {
  let source = @fs.read_file_to_string("./smt2/t219.smt2")
  ignore(parse_smtlib(source))
}

///|
test "dt_ayrat_1.smt2" {
  let source = @fs.read_file_to_string("./smt2/dt_ayrat_1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3396.smt2" {
  let source = @fs.read_file_to_string("./smt2/3396.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5724.smt2" {
  let source = @fs.read_file_to_string("./smt2/5724.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3104.smt2" {
  let source = @fs.read_file_to_string("./smt2/3104.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-3023.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-3023.smt2")
  ignore(parse_smtlib(source))
}

///|
test "lia2.smt2" {
  let source = @fs.read_file_to_string("./smt2/lia2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "incsat.smt2" {
  let source = @fs.read_file_to_string("./smt2/incsat.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string-concat.smt2" {
  let source = @fs.read_file_to_string("./smt2/string-concat.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6117-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/6117-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-36.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-36.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ieee_bv-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ieee_bv-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl55.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl55.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3972.smt2" {
  let source = @fs.read_file_to_string("./smt2/3972.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3384.smt2" {
  let source = @fs.read_file_to_string("./smt2/3384.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3503.smt2" {
  let source = @fs.read_file_to_string("./smt2/3503.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rounding_mode-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rounding_mode-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3632.smt2" {
  let source = @fs.read_file_to_string("./smt2/3632.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-quantifiers-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-quantifiers-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3930.smt2" {
  let source = @fs.read_file_to_string("./smt2/3930.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6079-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/6079-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "small-bv-quant-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/small-bv-quant-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-16.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t138.smt2" {
  let source = @fs.read_file_to_string("./smt2/t138.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t9.smt2" {
  let source = @fs.read_file_to_string("./smt2/t9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl3.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6674-simp.smt2" {
  let source = @fs.read_file_to_string("./smt2/6674-simp.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t173.smt2" {
  let source = @fs.read_file_to_string("./smt2/t173.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3849.smt2" {
  let source = @fs.read_file_to_string("./smt2/3849.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl26.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl26.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2962.smt2" {
  let source = @fs.read_file_to_string("./smt2/2962.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4841-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/4841-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.16.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t176.smt2" {
  let source = @fs.read_file_to_string("./smt2/t176.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-39.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-39.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o1.smt2" {
  let source = @fs.read_file_to_string("./smt2/o1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl43.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl43.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string12.smt2" {
  let source = @fs.read_file_to_string("./smt2/string12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3570.smt2" {
  let source = @fs.read_file_to_string("./smt2/3570.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3369.smt2" {
  let source = @fs.read_file_to_string("./smt2/3369.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-25.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-25.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3553.smt2" {
  let source = @fs.read_file_to_string("./smt2/3553.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3689.smt2" {
  let source = @fs.read_file_to_string("./smt2/3689.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.15.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine5.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-3028.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-3028.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3970.smt2" {
  let source = @fs.read_file_to_string("./smt2/3970.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-16.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "eq.smt2" {
  let source = @fs.read_file_to_string("./smt2/eq.smt2")
  ignore(parse_smtlib(source))
}

///|
test "mev_array.smt2" {
  let source = @fs.read_file_to_string("./smt2/mev_array.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3500.smt2" {
  let source = @fs.read_file_to_string("./smt2/3500.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string6.smt2" {
  let source = @fs.read_file_to_string("./smt2/string6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2531.smt2" {
  let source = @fs.read_file_to_string("./smt2/2531.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t205.smt2" {
  let source = @fs.read_file_to_string("./smt2/t205.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl27.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl27.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2420.smt2" {
  let source = @fs.read_file_to_string("./smt2/2420.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl51.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl51.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3210.smt2" {
  let source = @fs.read_file_to_string("./smt2/3210.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl40.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl40.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3886.smt2" {
  let source = @fs.read_file_to_string("./smt2/3886.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nira.smt2" {
  let source = @fs.read_file_to_string("./smt2/nira.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t146.smt2" {
  let source = @fs.read_file_to_string("./smt2/t146.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_real-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_real-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl1.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl34.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl34.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t199.smt2" {
  let source = @fs.read_file_to_string("./smt2/t199.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t191.smt2" {
  let source = @fs.read_file_to_string("./smt2/t191.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3986.smt2" {
  let source = @fs.read_file_to_string("./smt2/3986.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t178.smt2" {
  let source = @fs.read_file_to_string("./smt2/t178.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2548.smt2" {
  let source = @fs.read_file_to_string("./smt2/2548.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6117-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/6117-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2902.smt2" {
  let source = @fs.read_file_to_string("./smt2/2902.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3514.smt2" {
  let source = @fs.read_file_to_string("./smt2/3514.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string-ops.smt2" {
  let source = @fs.read_file_to_string("./smt2/string-ops.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t133.smt2" {
  let source = @fs.read_file_to_string("./smt2/t133.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.41.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.41.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3633.smt2" {
  let source = @fs.read_file_to_string("./smt2/3633.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3675.smt2" {
  let source = @fs.read_file_to_string("./smt2/3675.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3275.smt2" {
  let source = @fs.read_file_to_string("./smt2/3275.smt2")
  ignore(parse_smtlib(source))
}

///|
test "1846.smt2" {
  let source = @fs.read_file_to_string("./smt2/1846.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t184.smt2" {
  let source = @fs.read_file_to_string("./smt2/t184.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t196.smt2" {
  let source = @fs.read_file_to_string("./smt2/t196.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3547.smt2" {
  let source = @fs.read_file_to_string("./smt2/3547.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-29.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-29.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4004.smt2" {
  let source = @fs.read_file_to_string("./smt2/4004.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t206.smt2" {
  let source = @fs.read_file_to_string("./smt2/t206.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2561.smt2" {
  let source = @fs.read_file_to_string("./smt2/2561.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl18.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl18.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.39.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.39.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6670.smt2" {
  let source = @fs.read_file_to_string("./smt2/6670.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-20.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-20.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t172.smt2" {
  let source = @fs.read_file_to_string("./smt2/t172.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5731.smt2" {
  let source = @fs.read_file_to_string("./smt2/5731.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t123.smt2" {
  let source = @fs.read_file_to_string("./smt2/t123.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2960.smt2" {
  let source = @fs.read_file_to_string("./smt2/2960.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl58.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl58.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3625.smt2" {
  let source = @fs.read_file_to_string("./smt2/3625.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2923.smt2" {
  let source = @fs.read_file_to_string("./smt2/2923.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t130.smt2" {
  let source = @fs.read_file_to_string("./smt2/t130.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl7.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t212.smt2" {
  let source = @fs.read_file_to_string("./smt2/t212.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3971.smt2" {
  let source = @fs.read_file_to_string("./smt2/3971.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine8.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3118.smt2" {
  let source = @fs.read_file_to_string("./smt2/3118.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3523.smt2" {
  let source = @fs.read_file_to_string("./smt2/3523.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-18.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-18.smt2")
  ignore(parse_smtlib(source))
}

///|
test "strategy-default.smt2" {
  let source = @fs.read_file_to_string("./smt2/strategy-default.smt2")
  ignore(parse_smtlib(source))
}

///|
test "testmapi.smt2" {
  let source = @fs.read_file_to_string("./smt2/testmapi.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string11.smt2" {
  let source = @fs.read_file_to_string("./smt2/string11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string14.smt2" {
  let source = @fs.read_file_to_string("./smt2/string14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-27.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-27.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6196.smt2" {
  let source = @fs.read_file_to_string("./smt2/6196.smt2")
  ignore(parse_smtlib(source))
}

///|
test "pb.smt2" {
  let source = @fs.read_file_to_string("./smt2/pb.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3155.smt2" {
  let source = @fs.read_file_to_string("./smt2/3155.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3225.smt2" {
  let source = @fs.read_file_to_string("./smt2/3225.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3997.smt2" {
  let source = @fs.read_file_to_string("./smt2/3997.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-21.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-21.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl31.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl31.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3234.smt2" {
  let source = @fs.read_file_to_string("./smt2/3234.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-12.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-mul-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-mul-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3680.smt2" {
  let source = @fs.read_file_to_string("./smt2/3680.smt2")
  ignore(parse_smtlib(source))
}

///|
test "segfault2.smt2" {
  let source = @fs.read_file_to_string("./smt2/segfault2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3999.smt2" {
  let source = @fs.read_file_to_string("./smt2/3999.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t119.smt2" {
  let source = @fs.read_file_to_string("./smt2/t119.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3733.smt2" {
  let source = @fs.read_file_to_string("./smt2/3733.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-abs-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-abs-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine2.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3477.smt2" {
  let source = @fs.read_file_to_string("./smt2/3477.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3344.smt2" {
  let source = @fs.read_file_to_string("./smt2/3344.smt2")
  ignore(parse_smtlib(source))
}

///|
test "blinking_query.smt2" {
  let source = @fs.read_file_to_string("./smt2/blinking_query.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3748.smt2" {
  let source = @fs.read_file_to_string("./smt2/3748.smt2")
  ignore(parse_smtlib(source))
}

///|
test "div.smt2" {
  let source = @fs.read_file_to_string("./smt2/div.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3163.smt2" {
  let source = @fs.read_file_to_string("./smt2/3163.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3937.smt2" {
  let source = @fs.read_file_to_string("./smt2/3937.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3010.smt2" {
  let source = @fs.read_file_to_string("./smt2/3010.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4009.smt2" {
  let source = @fs.read_file_to_string("./smt2/4009.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5798.smt2" {
  let source = @fs.read_file_to_string("./smt2/5798.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-15.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3379.smt2" {
  let source = @fs.read_file_to_string("./smt2/3379.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3417.smt2" {
  let source = @fs.read_file_to_string("./smt2/3417.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3075.smt2" {
  let source = @fs.read_file_to_string("./smt2/3075.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6117-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/6117-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "consequences.smt2" {
  let source = @fs.read_file_to_string("./smt2/consequences.smt2")
  ignore(parse_smtlib(source))
}

///|
test "crash.smt2" {
  let source = @fs.read_file_to_string("./smt2/crash.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1566.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1566.smt2")
  ignore(parse_smtlib(source))
}

///|
test "dt2bv.smt2" {
  let source = @fs.read_file_to_string("./smt2/dt2bv.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4019.smt2" {
  let source = @fs.read_file_to_string("./smt2/4019.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3221.smt2" {
  let source = @fs.read_file_to_string("./smt2/3221.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl4.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3665.smt2" {
  let source = @fs.read_file_to_string("./smt2/3665.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2879.smt2" {
  let source = @fs.read_file_to_string("./smt2/2879.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t1.smt2" {
  let source = @fs.read_file_to_string("./smt2/t1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3223.smt2" {
  let source = @fs.read_file_to_string("./smt2/3223.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3587.smt2" {
  let source = @fs.read_file_to_string("./smt2/3587.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6116.smt2" {
  let source = @fs.read_file_to_string("./smt2/6116.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3438.smt2" {
  let source = @fs.read_file_to_string("./smt2/3438.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1538.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1538.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-neg.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-neg.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3827.smt2" {
  let source = @fs.read_file_to_string("./smt2/3827.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl29.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl29.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3260.smt2" {
  let source = @fs.read_file_to_string("./smt2/3260.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sub-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sub-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-13-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-13-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o4.smt2" {
  let source = @fs.read_file_to_string("./smt2/o4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3153.smt2" {
  let source = @fs.read_file_to_string("./smt2/3153.smt2")
  ignore(parse_smtlib(source))
}

///|
test "tan3.smt2" {
  let source = @fs.read_file_to_string("./smt2/tan3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "updt.smt2" {
  let source = @fs.read_file_to_string("./smt2/updt.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-mul-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-mul-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-13-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-13-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-13-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-13-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3name_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3name_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "macro-finder-cores.smt2" {
  let source = @fs.read_file_to_string("./smt2/macro-finder-cores.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3775.smt2" {
  let source = @fs.read_file_to_string("./smt2/3775.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3277.smt2" {
  let source = @fs.read_file_to_string("./smt2/3277.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-38.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-38.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-12.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3106.smt2" {
  let source = @fs.read_file_to_string("./smt2/3106.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4008.smt2" {
  let source = @fs.read_file_to_string("./smt2/4008.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t143.smt2" {
  let source = @fs.read_file_to_string("./smt2/t143.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3591.smt2" {
  let source = @fs.read_file_to_string("./smt2/3591.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t132.smt2" {
  let source = @fs.read_file_to_string("./smt2/t132.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2432.smt2" {
  let source = @fs.read_file_to_string("./smt2/2432.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine2.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl45.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl45.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2868.smt2" {
  let source = @fs.read_file_to_string("./smt2/2868.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-12.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl24.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl24.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-22.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-22.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5728.smt2" {
  let source = @fs.read_file_to_string("./smt2/5728.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-min-zero-zero-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-min-zero-zero-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2557.smt2" {
  let source = @fs.read_file_to_string("./smt2/2557.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3100.smt2" {
  let source = @fs.read_file_to_string("./smt2/3100.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t124.smt2" {
  let source = @fs.read_file_to_string("./smt2/t124.smt2")
  ignore(parse_smtlib(source))
}

///|
test "bvsmod.smt2" {
  let source = @fs.read_file_to_string("./smt2/bvsmod.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl48.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl48.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-18.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-18.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-30.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-30.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3218.smt2" {
  let source = @fs.read_file_to_string("./smt2/3218.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-19.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-19.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rounding_mode-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rounding_mode-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3391.smt2" {
  let source = @fs.read_file_to_string("./smt2/3391.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2890.smt2" {
  let source = @fs.read_file_to_string("./smt2/2890.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.40.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.40.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl2.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3312.smt2" {
  let source = @fs.read_file_to_string("./smt2/3312.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5721.smt2" {
  let source = @fs.read_file_to_string("./smt2/5721.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3889.smt2" {
  let source = @fs.read_file_to_string("./smt2/3889.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-div-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-div-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3342.smt2" {
  let source = @fs.read_file_to_string("./smt2/3342.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl32.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl32.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-signed-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-signed-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-26.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-26.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4017.smt2" {
  let source = @fs.read_file_to_string("./smt2/4017.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-min-zero-zero-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-min-zero-zero-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rounding_mode-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rounding_mode-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl30.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl30.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.17.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.17.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3834.smt2" {
  let source = @fs.read_file_to_string("./smt2/3834.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-15.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3301.smt2" {
  let source = @fs.read_file_to_string("./smt2/3301.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl12.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-14.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3282.smt2" {
  let source = @fs.read_file_to_string("./smt2/3282.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-13.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3504.smt2" {
  let source = @fs.read_file_to_string("./smt2/3504.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.5.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t211.smt2" {
  let source = @fs.read_file_to_string("./smt2/t211.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl49.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl49.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-min-zero-zero-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-min-zero-zero-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.34.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.34.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t175.smt2" {
  let source = @fs.read_file_to_string("./smt2/t175.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-34.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-34.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3521.smt2" {
  let source = @fs.read_file_to_string("./smt2/3521.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3688.smt2" {
  let source = @fs.read_file_to_string("./smt2/3688.smt2")
  ignore(parse_smtlib(source))
}

///|
test "root-pre.smt2" {
  let source = @fs.read_file_to_string("./smt2/root-pre.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2417.smt2" {
  let source = @fs.read_file_to_string("./smt2/2417.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6553-2-simp.smt2" {
  let source = @fs.read_file_to_string("./smt2/6553-2-simp.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3383.smt2" {
  let source = @fs.read_file_to_string("./smt2/3383.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl56.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl56.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-predicates.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-predicates.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3524.smt2" {
  let source = @fs.read_file_to_string("./smt2/3524.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t213.smt2" {
  let source = @fs.read_file_to_string("./smt2/t213.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3241.smt2" {
  let source = @fs.read_file_to_string("./smt2/3241.smt2")
  ignore(parse_smtlib(source))
}

///|
test "model_compact_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/model_compact_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "tan.smt2" {
  let source = @fs.read_file_to_string("./smt2/tan.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3123.smt2" {
  let source = @fs.read_file_to_string("./smt2/3123.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3247.smt2" {
  let source = @fs.read_file_to_string("./smt2/3247.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t139.smt2" {
  let source = @fs.read_file_to_string("./smt2/t139.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3973.smt2" {
  let source = @fs.read_file_to_string("./smt2/3973.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3601.smt2" {
  let source = @fs.read_file_to_string("./smt2/3601.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3752.smt2" {
  let source = @fs.read_file_to_string("./smt2/3752.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-datatype_with_float-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-datatype_with_float-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine7.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2856.smt2" {
  let source = @fs.read_file_to_string("./smt2/2856.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2560.smt2" {
  let source = @fs.read_file_to_string("./smt2/2560.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t112.smt2" {
  let source = @fs.read_file_to_string("./smt2/t112.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3917.smt2" {
  let source = @fs.read_file_to_string("./smt2/3917.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-14.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6117-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/6117-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl10.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-27.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-27.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl47.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl47.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t189.smt2" {
  let source = @fs.read_file_to_string("./smt2/t189.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-20.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-20.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.30.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.30.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.20.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.20.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2530.smt2" {
  let source = @fs.read_file_to_string("./smt2/2530.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.43.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.43.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6117-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/6117-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4032.smt2" {
  let source = @fs.read_file_to_string("./smt2/4032.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3226.smt2" {
  let source = @fs.read_file_to_string("./smt2/3226.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6052.smt2" {
  let source = @fs.read_file_to_string("./smt2/6052.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-13-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-13-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "qffp-quant.smt2" {
  let source = @fs.read_file_to_string("./smt2/qffp-quant.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-3038.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-3038.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3529.smt2" {
  let source = @fs.read_file_to_string("./smt2/3529.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3115.smt2" {
  let source = @fs.read_file_to_string("./smt2/3115.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-max-zero-zero-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-max-zero-zero-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3626.smt2" {
  let source = @fs.read_file_to_string("./smt2/3626.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-32.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-32.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3458.smt2" {
  let source = @fs.read_file_to_string("./smt2/3458.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-18.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-18.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4021.smt2" {
  let source = @fs.read_file_to_string("./smt2/4021.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-963.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-963.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-tests-double-partial.smt2" {
  let source = @fs.read_file_to_string(
    "./smt2/fp-rem-tests-double-partial.smt2",
  )
  ignore(parse_smtlib(source))
}

///|
test "3538.smt2" {
  let source = @fs.read_file_to_string("./smt2/3538.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine3.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3434.smt2" {
  let source = @fs.read_file_to_string("./smt2/3434.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3339.smt2" {
  let source = @fs.read_file_to_string("./smt2/3339.smt2")
  ignore(parse_smtlib(source))
}

///|
test "re_rewriter.smt2" {
  let source = @fs.read_file_to_string("./smt2/re_rewriter.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-28.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-28.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6079-1-simp.smt2" {
  let source = @fs.read_file_to_string("./smt2/6079-1-simp.smt2")
  ignore(parse_smtlib(source))
}

///|
test "core2.smt2" {
  let source = @fs.read_file_to_string("./smt2/core2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sub.smt2" {
  let source = @fs.read_file_to_string("./smt2/sub.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-14.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6079-8-simp.smt2" {
  let source = @fs.read_file_to_string("./smt2/6079-8-simp.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t125.smt2" {
  let source = @fs.read_file_to_string("./smt2/t125.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3759.smt2" {
  let source = @fs.read_file_to_string("./smt2/3759.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o6.smt2" {
  let source = @fs.read_file_to_string("./smt2/o6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o5.smt2" {
  let source = @fs.read_file_to_string("./smt2/o5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2990.smt2" {
  let source = @fs.read_file_to_string("./smt2/2990.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.31.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.31.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.37.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.37.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t158.smt2" {
  let source = @fs.read_file_to_string("./smt2/t158.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-quantifiers-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-quantifiers-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sqrt-bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/sqrt-bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_real-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_real-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "ule.smt2" {
  let source = @fs.read_file_to_string("./smt2/ule.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3749.smt2" {
  let source = @fs.read_file_to_string("./smt2/3749.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t109.smt2" {
  let source = @fs.read_file_to_string("./smt2/t109.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl25.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl25.smt2")
  ignore(parse_smtlib(source))
}

///|
test "7489.smt2" {
  let source = @fs.read_file_to_string("./smt2/7489.smt2")
  ignore(parse_smtlib(source))
}

///|
test "trig-bounds.smt2" {
  let source = @fs.read_file_to_string("./smt2/trig-bounds.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1086.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1086.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t209.smt2" {
  let source = @fs.read_file_to_string("./smt2/t209.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2924.smt2" {
  let source = @fs.read_file_to_string("./smt2/2924.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3896.smt2" {
  let source = @fs.read_file_to_string("./smt2/3896.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl37.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl37.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3127.smt2" {
  let source = @fs.read_file_to_string("./smt2/3127.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t193.smt2" {
  let source = @fs.read_file_to_string("./smt2/t193.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1733.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1733.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.29.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.29.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3555.smt2" {
  let source = @fs.read_file_to_string("./smt2/3555.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t207.smt2" {
  let source = @fs.read_file_to_string("./smt2/t207.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3440.smt2" {
  let source = @fs.read_file_to_string("./smt2/3440.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "abs.smt2" {
  let source = @fs.read_file_to_string("./smt2/abs.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.4.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t197.smt2" {
  let source = @fs.read_file_to_string("./smt2/t197.smt2")
  ignore(parse_smtlib(source))
}

///|
test "trig-spherical.smt2" {
  let source = @fs.read_file_to_string("./smt2/trig-spherical.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-13.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "bvcore.smt2" {
  let source = @fs.read_file_to_string("./smt2/bvcore.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4041.smt2" {
  let source = @fs.read_file_to_string("./smt2/4041.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3141.smt2" {
  let source = @fs.read_file_to_string("./smt2/3141.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-20.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-20.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3190.smt2" {
  let source = @fs.read_file_to_string("./smt2/3190.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t145.smt2" {
  let source = @fs.read_file_to_string("./smt2/t145.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t169.smt2" {
  let source = @fs.read_file_to_string("./smt2/t169.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine4.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string13.smt2" {
  let source = @fs.read_file_to_string("./smt2/string13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t174.smt2" {
  let source = @fs.read_file_to_string("./smt2/t174.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine6.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.38.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.38.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-tests-single-non-partial.smt2" {
  let source = @fs.read_file_to_string(
    "./smt2/fp-rem-tests-single-non-partial.smt2",
  )
  ignore(parse_smtlib(source))
}

///|
test "power-zero-safe.smt2" {
  let source = @fs.read_file_to_string("./smt2/power-zero-safe.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3517.smt2" {
  let source = @fs.read_file_to_string("./smt2/3517.smt2")
  ignore(parse_smtlib(source))
}

///|
test "atan.smt2" {
  let source = @fs.read_file_to_string("./smt2/atan.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6336.smt2" {
  let source = @fs.read_file_to_string("./smt2/6336.smt2")
  ignore(parse_smtlib(source))
}

///|
test "627.smt2" {
  let source = @fs.read_file_to_string("./smt2/627.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1218.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1218.smt2")
  ignore(parse_smtlib(source))
}

///|
test "segfaults2_minimal.smt2" {
  let source = @fs.read_file_to_string("./smt2/segfaults2_minimal.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fp-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fp-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3237.smt2" {
  let source = @fs.read_file_to_string("./smt2/3237.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3081.smt2" {
  let source = @fs.read_file_to_string("./smt2/3081.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3934.smt2" {
  let source = @fs.read_file_to_string("./smt2/3934.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1846.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1846.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1092.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1092.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t181.smt2" {
  let source = @fs.read_file_to_string("./smt2/t181.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4841-simp.smt2" {
  let source = @fs.read_file_to_string("./smt2/4841-simp.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl59.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl59.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t114.smt2" {
  let source = @fs.read_file_to_string("./smt2/t114.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t180.smt2" {
  let source = @fs.read_file_to_string("./smt2/t180.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-31.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-31.smt2")
  ignore(parse_smtlib(source))
}

///|
test "attr_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/attr_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl35.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl35.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl50.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl50.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1694.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1694.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3332.smt2" {
  let source = @fs.read_file_to_string("./smt2/3332.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3785.smt2" {
  let source = @fs.read_file_to_string("./smt2/3785.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string3.smt2" {
  let source = @fs.read_file_to_string("./smt2/string3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-div-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-div-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-41.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-41.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "8099.smt2" {
  let source = @fs.read_file_to_string("./smt2/8099.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t208.smt2" {
  let source = @fs.read_file_to_string("./smt2/t208.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-pzero.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-pzero.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2520.smt2" {
  let source = @fs.read_file_to_string("./smt2/2520.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t131.smt2" {
  let source = @fs.read_file_to_string("./smt2/t131.smt2")
  ignore(parse_smtlib(source))
}

///|
test "bv0.smt2" {
  let source = @fs.read_file_to_string("./smt2/bv0.smt2")
  ignore(parse_smtlib(source))
}

///|
test "qfbv-quant.smt2" {
  let source = @fs.read_file_to_string("./smt2/qfbv-quant.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t102.smt2" {
  let source = @fs.read_file_to_string("./smt2/t102.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3549.smt2" {
  let source = @fs.read_file_to_string("./smt2/3549.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3286.smt2" {
  let source = @fs.read_file_to_string("./smt2/3286.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t195.smt2" {
  let source = @fs.read_file_to_string("./smt2/t195.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t11.smt2" {
  let source = @fs.read_file_to_string("./smt2/t11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-25.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-25.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "mbqi_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/mbqi_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3672.smt2" {
  let source = @fs.read_file_to_string("./smt2/3672.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1224.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1224.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1677.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1677.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3960.smt2" {
  let source = @fs.read_file_to_string("./smt2/3960.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t215.smt2" {
  let source = @fs.read_file_to_string("./smt2/t215.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3607.smt2" {
  let source = @fs.read_file_to_string("./smt2/3607.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string9.smt2" {
  let source = @fs.read_file_to_string("./smt2/string9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-790.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-790.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3473.smt2" {
  let source = @fs.read_file_to_string("./smt2/3473.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-ninf.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-ninf.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1729.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1729.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3502.smt2" {
  let source = @fs.read_file_to_string("./smt2/3502.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3967.smt2" {
  let source = @fs.read_file_to_string("./smt2/3967.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3754.smt2" {
  let source = @fs.read_file_to_string("./smt2/3754.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl15.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3249.smt2" {
  let source = @fs.read_file_to_string("./smt2/3249.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-min-zero-zero-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-min-zero-zero-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t185.smt2" {
  let source = @fs.read_file_to_string("./smt2/t185.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t104.smt2" {
  let source = @fs.read_file_to_string("./smt2/t104.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1683.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1683.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2447.smt2" {
  let source = @fs.read_file_to_string("./smt2/2447.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-add-sub.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-add-sub.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t160.smt2" {
  let source = @fs.read_file_to_string("./smt2/t160.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "mul.smt2" {
  let source = @fs.read_file_to_string("./smt2/mul.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl13.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3105.smt2" {
  let source = @fs.read_file_to_string("./smt2/3105.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-24.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-24.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-23.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-23.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3559.smt2" {
  let source = @fs.read_file_to_string("./smt2/3559.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-nzero.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-nzero.smt2")
  ignore(parse_smtlib(source))
}

///|
test "array.smt2" {
  let source = @fs.read_file_to_string("./smt2/array.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2912.smt2" {
  let source = @fs.read_file_to_string("./smt2/2912.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine6.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3573.smt2" {
  let source = @fs.read_file_to_string("./smt2/3573.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2891.smt2" {
  let source = @fs.read_file_to_string("./smt2/2891.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "testmap.smt2" {
  let source = @fs.read_file_to_string("./smt2/testmap.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t115.smt2" {
  let source = @fs.read_file_to_string("./smt2/t115.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-14.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2937.smt2" {
  let source = @fs.read_file_to_string("./smt2/2937.smt2")
  ignore(parse_smtlib(source))
}

///|
test "token3.smt2" {
  let source = @fs.read_file_to_string("./smt2/token3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3576.smt2" {
  let source = @fs.read_file_to_string("./smt2/3576.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3436.smt2" {
  let source = @fs.read_file_to_string("./smt2/3436.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2889.smt2" {
  let source = @fs.read_file_to_string("./smt2/2889.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3572.smt2" {
  let source = @fs.read_file_to_string("./smt2/3572.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4841-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/4841-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-24.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-24.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3799.smt2" {
  let source = @fs.read_file_to_string("./smt2/3799.smt2")
  ignore(parse_smtlib(source))
}

///|
test "cosine7.smt2" {
  let source = @fs.read_file_to_string("./smt2/cosine7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-33.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-33.smt2")
  ignore(parse_smtlib(source))
}

///|
test "ho.smt2" {
  let source = @fs.read_file_to_string("./smt2/ho.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-17.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-17.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-div-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-div-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3111.smt2" {
  let source = @fs.read_file_to_string("./smt2/3111.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sqrt-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sqrt-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3411.smt2" {
  let source = @fs.read_file_to_string("./smt2/3411.smt2")
  ignore(parse_smtlib(source))
}

///|
test "const_array_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/const_array_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2892.smt2" {
  let source = @fs.read_file_to_string("./smt2/2892.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl36.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl36.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6728-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/6728-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3255.smt2" {
  let source = @fs.read_file_to_string("./smt2/3255.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3751.smt2" {
  let source = @fs.read_file_to_string("./smt2/3751.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine9.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "re.smt2" {
  let source = @fs.read_file_to_string("./smt2/re.smt2")
  ignore(parse_smtlib(source))
}

///|
test "arith_bug2.smt2" {
  let source = @fs.read_file_to_string("./smt2/arith_bug2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3125.smt2" {
  let source = @fs.read_file_to_string("./smt2/3125.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.28.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.28.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-max-zero-zero-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-max-zero-zero-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t217.smt2" {
  let source = @fs.read_file_to_string("./smt2/t217.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl19.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl19.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "lia1.smt2" {
  let source = @fs.read_file_to_string("./smt2/lia1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4003.smt2" {
  let source = @fs.read_file_to_string("./smt2/4003.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3709.smt2" {
  let source = @fs.read_file_to_string("./smt2/3709.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine5.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t16.smt2" {
  let source = @fs.read_file_to_string("./smt2/t16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl17.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl17.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t117.smt2" {
  let source = @fs.read_file_to_string("./smt2/t117.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t171.smt2" {
  let source = @fs.read_file_to_string("./smt2/t171.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2533.smt2" {
  let source = @fs.read_file_to_string("./smt2/2533.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3006.smt2" {
  let source = @fs.read_file_to_string("./smt2/3006.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4010.smt2" {
  let source = @fs.read_file_to_string("./smt2/4010.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_float-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_float-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3569.smt2" {
  let source = @fs.read_file_to_string("./smt2/3569.smt2")
  ignore(parse_smtlib(source))
}

///|
test "arith_bug.smt2" {
  let source = @fs.read_file_to_string("./smt2/arith_bug.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue2301.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue2301.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3267.smt2" {
  let source = @fs.read_file_to_string("./smt2/3267.smt2")
  ignore(parse_smtlib(source))
}

///|
test "strategy-par-or-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/strategy-par-or-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-35.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-35.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-nan.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-nan.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string-simplify.smt2" {
  let source = @fs.read_file_to_string("./smt2/string-simplify.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t111.smt2" {
  let source = @fs.read_file_to_string("./smt2/t111.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3303.smt2" {
  let source = @fs.read_file_to_string("./smt2/3303.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3252.smt2" {
  let source = @fs.read_file_to_string("./smt2/3252.smt2")
  ignore(parse_smtlib(source))
}

///|
test "memset.smt2" {
  let source = @fs.read_file_to_string("./smt2/memset.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.2.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3532.smt2" {
  let source = @fs.read_file_to_string("./smt2/3532.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t210.smt2" {
  let source = @fs.read_file_to_string("./smt2/t210.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-19.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-19.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2919.smt2" {
  let source = @fs.read_file_to_string("./smt2/2919.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3148.smt2" {
  let source = @fs.read_file_to_string("./smt2/3148.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3209.smt2" {
  let source = @fs.read_file_to_string("./smt2/3209.smt2")
  ignore(parse_smtlib(source))
}

///|
test "tan2.smt2" {
  let source = @fs.read_file_to_string("./smt2/tan2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2935.smt2" {
  let source = @fs.read_file_to_string("./smt2/2935.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3028.smt2" {
  let source = @fs.read_file_to_string("./smt2/3028.smt2")
  ignore(parse_smtlib(source))
}

///|
test "dt_ayrat_4.smt2" {
  let source = @fs.read_file_to_string("./smt2/dt_ayrat_4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t154.smt2" {
  let source = @fs.read_file_to_string("./smt2/t154.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3705.smt2" {
  let source = @fs.read_file_to_string("./smt2/3705.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.53.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.53.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3113.smt2" {
  let source = @fs.read_file_to_string("./smt2/3113.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1658.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1658.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3294.smt2" {
  let source = @fs.read_file_to_string("./smt2/3294.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "bad_set_logic.smt2" {
  let source = @fs.read_file_to_string("./smt2/bad_set_logic.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t214.smt2" {
  let source = @fs.read_file_to_string("./smt2/t214.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.1.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t190.smt2" {
  let source = @fs.read_file_to_string("./smt2/t190.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3335.smt2" {
  let source = @fs.read_file_to_string("./smt2/3335.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2838.smt2" {
  let source = @fs.read_file_to_string("./smt2/2838.smt2")
  ignore(parse_smtlib(source))
}

///|
test "trig-quadrants.smt2" {
  let source = @fs.read_file_to_string("./smt2/trig-quadrants.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-3106.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-3106.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-min-zero-zero-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-min-zero-zero-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "dt_ayrat_3.smt2" {
  let source = @fs.read_file_to_string("./smt2/dt_ayrat_3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2556.smt2" {
  let source = @fs.read_file_to_string("./smt2/2556.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.14.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4033.smt2" {
  let source = @fs.read_file_to_string("./smt2/4033.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3336.smt2" {
  let source = @fs.read_file_to_string("./smt2/3336.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-mul-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-mul-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3933.smt2" {
  let source = @fs.read_file_to_string("./smt2/3933.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl9.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "power.smt2" {
  let source = @fs.read_file_to_string("./smt2/power.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string-literals.smt2" {
  let source = @fs.read_file_to_string("./smt2/string-literals.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl57.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl57.smt2")
  ignore(parse_smtlib(source))
}

///|
test "loop.smt2" {
  let source = @fs.read_file_to_string("./smt2/loop.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3385.smt2" {
  let source = @fs.read_file_to_string("./smt2/3385.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-datatype_with_float-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-datatype_with_float-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-17.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-17.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-roundToIntegral-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-roundToIntegral-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3220.smt2" {
  let source = @fs.read_file_to_string("./smt2/3220.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl44.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl44.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6079-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/6079-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-lt-gt.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-lt-gt.smt2")
  ignore(parse_smtlib(source))
}

///|
test "sine4.smt2" {
  let source = @fs.read_file_to_string("./smt2/sine4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-15.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-21.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-21.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1816.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1816.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-16.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "pat2.smt2" {
  let source = @fs.read_file_to_string("./smt2/pat2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t135.smt2" {
  let source = @fs.read_file_to_string("./smt2/t135.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl38.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl38.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t168.smt2" {
  let source = @fs.read_file_to_string("./smt2/t168.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4044.smt2" {
  let source = @fs.read_file_to_string("./smt2/4044.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-max-zero-zero-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-max-zero-zero-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2478.smt2" {
  let source = @fs.read_file_to_string("./smt2/2478.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-div-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-div-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3642.smt2" {
  let source = @fs.read_file_to_string("./smt2/3642.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-sorts-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-sorts-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-16.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl54.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl54.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t148.smt2" {
  let source = @fs.read_file_to_string("./smt2/t148.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3984.smt2" {
  let source = @fs.read_file_to_string("./smt2/3984.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-40.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-40.smt2")
  ignore(parse_smtlib(source))
}

///|
test "testfoldl.smt2" {
  let source = @fs.read_file_to_string("./smt2/testfoldl.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3742.smt2" {
  let source = @fs.read_file_to_string("./smt2/3742.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "power-sqrt-unsafe.smt2" {
  let source = @fs.read_file_to_string("./smt2/power-sqrt-unsafe.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-16.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3324.smt2" {
  let source = @fs.read_file_to_string("./smt2/3324.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4013.smt2" {
  let source = @fs.read_file_to_string("./smt2/4013.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2943.smt2" {
  let source = @fs.read_file_to_string("./smt2/2943.smt2")
  ignore(parse_smtlib(source))
}

///|
test "b1.smt2" {
  let source = @fs.read_file_to_string("./smt2/b1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "blinking_query2.smt2" {
  let source = @fs.read_file_to_string("./smt2/blinking_query2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t134.smt2" {
  let source = @fs.read_file_to_string("./smt2/t134.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1851.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1851.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3919.smt2" {
  let source = @fs.read_file_to_string("./smt2/3919.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6054.smt2" {
  let source = @fs.read_file_to_string("./smt2/6054.smt2")
  ignore(parse_smtlib(source))
}

///|
test "asin.smt2" {
  let source = @fs.read_file_to_string("./smt2/asin.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3959.smt2" {
  let source = @fs.read_file_to_string("./smt2/3959.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_float-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_float-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3700.smt2" {
  let source = @fs.read_file_to_string("./smt2/3700.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t8.smt2" {
  let source = @fs.read_file_to_string("./smt2/t8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl21.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl21.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3137.smt2" {
  let source = @fs.read_file_to_string("./smt2/3137.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t201.smt2" {
  let source = @fs.read_file_to_string("./smt2/t201.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3735.smt2" {
  let source = @fs.read_file_to_string("./smt2/3735.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6902.smt2" {
  let source = @fs.read_file_to_string("./smt2/6902.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1725.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1725.smt2")
  ignore(parse_smtlib(source))
}

///|
test "4015.smt2" {
  let source = @fs.read_file_to_string("./smt2/4015.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3663.smt2" {
  let source = @fs.read_file_to_string("./smt2/3663.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-feature-check-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-feature-check-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t150.smt2" {
  let source = @fs.read_file_to_string("./smt2/t150.smt2")
  ignore(parse_smtlib(source))
}

///|
test "acos.smt2" {
  let source = @fs.read_file_to_string("./smt2/acos.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-12.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3832.smt2" {
  let source = @fs.read_file_to_string("./smt2/3832.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3816.smt2" {
  let source = @fs.read_file_to_string("./smt2/3816.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5075.smt2" {
  let source = @fs.read_file_to_string("./smt2/5075.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2883.smt2" {
  let source = @fs.read_file_to_string("./smt2/2883.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-8.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-4.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-4.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5693.smt2" {
  let source = @fs.read_file_to_string("./smt2/5693.smt2")
  ignore(parse_smtlib(source))
}

///|
test "epsilon.smt2" {
  let source = @fs.read_file_to_string("./smt2/epsilon.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2567.smt2" {
  let source = @fs.read_file_to_string("./smt2/2567.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3765.smt2" {
  let source = @fs.read_file_to_string("./smt2/3765.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t192.smt2" {
  let source = @fs.read_file_to_string("./smt2/t192.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string-eval.smt2" {
  let source = @fs.read_file_to_string("./smt2/string-eval.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t216.smt2" {
  let source = @fs.read_file_to_string("./smt2/t216.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-26.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-26.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3253.smt2" {
  let source = @fs.read_file_to_string("./smt2/3253.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl-simp.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl-simp.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-array-3.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-array-3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.12.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.12.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-628.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-628.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2877.smt2" {
  let source = @fs.read_file_to_string("./smt2/2877.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl28.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl28.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-abs-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-abs-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl41.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl41.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-14.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "unsatcore.smt2" {
  let source = @fs.read_file_to_string("./smt2/unsatcore.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2955.smt2" {
  let source = @fs.read_file_to_string("./smt2/2955.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2415.smt2" {
  let source = @fs.read_file_to_string("./smt2/2415.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl39.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl39.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-operations.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-operations.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3422.smt2" {
  let source = @fs.read_file_to_string("./smt2/3422.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl16.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl16.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.6.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t151.smt2" {
  let source = @fs.read_file_to_string("./smt2/t151.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3825.smt2" {
  let source = @fs.read_file_to_string("./smt2/3825.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.52.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.52.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_sbv-11.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_sbv-11.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t122.smt2" {
  let source = @fs.read_file_to_string("./smt2/t122.smt2")
  ignore(parse_smtlib(source))
}

///|
test "z3.26.smt2" {
  let source = @fs.read_file_to_string("./smt2/z3.26.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3423.smt2" {
  let source = @fs.read_file_to_string("./smt2/3423.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3732.smt2" {
  let source = @fs.read_file_to_string("./smt2/3732.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl20.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl20.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2573.smt2" {
  let source = @fs.read_file_to_string("./smt2/2573.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-2416-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-2416-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-13.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-13.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1699.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1699.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t194.smt2" {
  let source = @fs.read_file_to_string("./smt2/t194.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3968.smt2" {
  let source = @fs.read_file_to_string("./smt2/3968.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3509.smt2" {
  let source = @fs.read_file_to_string("./smt2/3509.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl5.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3146.smt2" {
  let source = @fs.read_file_to_string("./smt2/3146.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t103.smt2" {
  let source = @fs.read_file_to_string("./smt2/t103.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "0xff.smt2" {
  let source = @fs.read_file_to_string("./smt2/0xff.smt2")
  ignore(parse_smtlib(source))
}

///|
test "string-itos.smt2" {
  let source = @fs.read_file_to_string("./smt2/string-itos.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3279.smt2" {
  let source = @fs.read_file_to_string("./smt2/3279.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-le-ge.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-le-ge.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-pinf.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-pinf.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2939.smt2" {
  let source = @fs.read_file_to_string("./smt2/2939.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o3.smt2" {
  let source = @fs.read_file_to_string("./smt2/o3.smt2")
  ignore(parse_smtlib(source))
}

///|
test "bad_patterns.smt2" {
  let source = @fs.read_file_to_string("./smt2/bad_patterns.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1458.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1458.smt2")
  ignore(parse_smtlib(source))
}

///|
test "o7.smt2" {
  let source = @fs.read_file_to_string("./smt2/o7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ieee_bv-2.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ieee_bv-2.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6116-float.smt2" {
  let source = @fs.read_file_to_string("./smt2/6116-float.smt2")
  ignore(parse_smtlib(source))
}

///|
test "5710.smt2" {
  let source = @fs.read_file_to_string("./smt2/5710.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-10.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-10.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-conversions-15.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-conversions-15.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3154.smt2" {
  let source = @fs.read_file_to_string("./smt2/3154.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3362.smt2" {
  let source = @fs.read_file_to_string("./smt2/3362.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3401.smt2" {
  let source = @fs.read_file_to_string("./smt2/3401.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3244.smt2" {
  let source = @fs.read_file_to_string("./smt2/3244.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl14.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t14.smt2" {
  let source = @fs.read_file_to_string("./smt2/t14.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3397.smt2" {
  let source = @fs.read_file_to_string("./smt2/3397.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-uf-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-uf-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6117-5.smt2" {
  let source = @fs.read_file_to_string("./smt2/6117-5.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3264.smt2" {
  let source = @fs.read_file_to_string("./smt2/3264.smt2")
  ignore(parse_smtlib(source))
}

///|
test "intervalDownDivide.smt2" {
  let source = @fs.read_file_to_string("./smt2/intervalDownDivide.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3175.smt2" {
  let source = @fs.read_file_to_string("./smt2/3175.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_unsigned-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_unsigned-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-fma-7.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-fma-7.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3527.smt2" {
  let source = @fs.read_file_to_string("./smt2/3527.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t182.smt2" {
  let source = @fs.read_file_to_string("./smt2/t182.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2549.smt2" {
  let source = @fs.read_file_to_string("./smt2/2549.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3299.smt2" {
  let source = @fs.read_file_to_string("./smt2/3299.smt2")
  ignore(parse_smtlib(source))
}

///|
test "6079-9.smt2" {
  let source = @fs.read_file_to_string("./smt2/6079-9.smt2")
  ignore(parse_smtlib(source))
}

///|
test "elim-uncnstr-tactic.smt2" {
  let source = @fs.read_file_to_string("./smt2/elim-uncnstr-tactic.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-23.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-23.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3929.smt2" {
  let source = @fs.read_file_to_string("./smt2/3929.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t170.smt2" {
  let source = @fs.read_file_to_string("./smt2/t170.smt2")
  ignore(parse_smtlib(source))
}

///|
test "nl22.smt2" {
  let source = @fs.read_file_to_string("./smt2/nl22.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1608.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1608.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3738.smt2" {
  let source = @fs.read_file_to_string("./smt2/3738.smt2")
  ignore(parse_smtlib(source))
}

///|
test "2431.smt2" {
  let source = @fs.read_file_to_string("./smt2/2431.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3597.smt2" {
  let source = @fs.read_file_to_string("./smt2/3597.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3554.smt2" {
  let source = @fs.read_file_to_string("./smt2/3554.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3378.smt2" {
  let source = @fs.read_file_to_string("./smt2/3378.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_fp_simplifier.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_fp_simplifier.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-29.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-29.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3620.smt2" {
  let source = @fs.read_file_to_string("./smt2/3620.smt2")
  ignore(parse_smtlib(source))
}

///|
test "t177.smt2" {
  let source = @fs.read_file_to_string("./smt2/t177.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-to_ubv-31.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-to_ubv-31.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-rem-6.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-rem-6.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3862.smt2" {
  let source = @fs.read_file_to_string("./smt2/3862.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-eq-1.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-eq-1.smt2")
  ignore(parse_smtlib(source))
}

///|
test "issue-1681.smt2" {
  let source = @fs.read_file_to_string("./smt2/issue-1681.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3713.smt2" {
  let source = @fs.read_file_to_string("./smt2/3713.smt2")
  ignore(parse_smtlib(source))
}

///|
test "coercions.smt2" {
  let source = @fs.read_file_to_string("./smt2/coercions.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3891.smt2" {
  let source = @fs.read_file_to_string("./smt2/3891.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3985.smt2" {
  let source = @fs.read_file_to_string("./smt2/3985.smt2")
  ignore(parse_smtlib(source))
}

///|
test "3982.smt2" {
  let source = @fs.read_file_to_string("./smt2/3982.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-template.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-template.smt2")
  ignore(parse_smtlib(source))
}

///|
test "fp-model_evaluator_8.smt2" {
  let source = @fs.read_file_to_string("./smt2/fp-model_evaluator_8.smt2")
  ignore(parse_smtlib(source))
}
