///|
test "2557" {
  run_smt("2557")
}

///|
test "t130" {
  run_smt("t130")
}

///|
test "3103" {
  run_smt("3103")
}

///|
test "t111" {
  run_smt("t111")
}

///|
test "fp-rem-5" {
  run_smt("fp-rem-5")
}

///|
test "mul" {
  run_smt("mul")
}

// =========================================================
// =========================================================

///|
test "2546" {
  run_smt("2546")
}

///|
test "z3.27" {
  run_smt("z3.27")
}

///|
test "mut_rec4sdk_output1" {
  run_smt("mut_rec4sdk_output1")
}

///|
test "3670" {
  run_smt("3670")
}

///|
test "4000" {
  run_smt("4000")
}

///|
test "intervalUpDivide" {
  run_smt("intervalUpDivide")
}

///|
test "fp-conversions-4" {
  run_smt("fp-conversions-4")
}

///|
test "fp-roundToIntegral-7" {
  run_smt("fp-roundToIntegral-7")
}

///|
test "fp-fma-17" {
  run_smt("fp-fma-17")
}

///|
test "error" {
  run_smt("error")
}

///|
test "fp-array-1" {
  run_smt("fp-array-1")
}

///|
test "3101" {
  run_smt("3101")
}

///|
test "rec" {
  run_smt("rec")
}

///|
test "3858" {
  run_smt("3858")
}

///|
test "3730" {
  run_smt("3730")
}

///|
test "nl33" {
  run_smt("nl33")
}

///|
test "fp-roundToIntegral-1" {
  run_smt("fp-roundToIntegral-1")
}

///|
test "string7" {
  run_smt("string7")
}

///|
test "fp-conversions-1" {
  run_smt("fp-conversions-1")
}

///|
test "fp-sqrt-6" {
  run_smt("fp-sqrt-6")
}

///|
test "fp-uf-3" {
  run_smt("fp-uf-3")
}

///|
test "3589" {
  run_smt("3589")
}

///|
test "fp-datatype_with_float-4" {
  run_smt("fp-datatype_with_float-4")
}

///|
test "fp-to_fp-8" {
  run_smt("fp-to_fp-8")
}

///|
test "fp-to_sbv-13" {
  run_smt("fp-to_sbv-13")
}

///|
test "fp-uf-1" {
  run_smt("fp-uf-1")
}

///|
test "3420" {
  run_smt("3420")
}

///|
test "4020" {
  run_smt("4020")
}

///|
test "6582" {
  run_smt("6582")
}

///|
test "dejan_bug" {
  run_smt("dejan_bug")
}

///|
test "issue-1841" {
  run_smt("issue-1841")
}

///|
test "z3.25" {
  run_smt("z3.25")
}

///|
test "t155" {
  run_smt("t155")
}

///|
test "nl53" {
  run_smt("nl53")
}

///|
test "t144" {
  run_smt("t144")
}

///|
test "nl6" {
  run_smt("nl6")
}

///|
test "fp-uf-9" {
  run_smt("fp-uf-9")
}

///|
test "2343" {
  run_smt("2343")
}

///|
test "3215" {
  run_smt("3215")
}

///|
test "3238" {
  run_smt("3238")
}

///|
test "3402" {
  run_smt("3402")
}

///|
test "fp-datatype_with_float-1" {
  run_smt("fp-datatype_with_float-1")
}

///|
test "issue-1665" {
  run_smt("issue-1665")
}

///|
test "2956" {
  run_smt("2956")
}

///|
test "3695" {
  run_smt("3695")
}

///|
test "fp-to_ubv-17" {
  run_smt("fp-to_ubv-17")
}

///|
test "3645" {
  run_smt("3645")
}

///|
test "pat1" {
  run_smt("pat1")
}

///|
test "fp-array-5" {
  run_smt("fp-array-5")
}

///|
test "fp-sqrt-1" {
  run_smt("fp-sqrt-1")
}

///|
test "consequence_fd" {
  run_smt("consequence_fd")
}

///|
test "t183" {
  run_smt("t183")
}

///|
test "fp-to_fp_float-2" {
  run_smt("fp-to_fp_float-2")
}

///|
test "strategy-par-or-1" {
  run_smt("strategy-par-or-1")
}

///|
test "3120" {
  run_smt("3120")
}

///|
test "3158" {
  run_smt("3158")
}

///|
test "chain" {
  run_smt("chain")
}

///|
test "3911" {
  run_smt("3911")
}

///|
test "nl8" {
  run_smt("nl8")
}

///|
test "fp-eq-2" {
  run_smt("fp-eq-2")
}

///|
test "6593" {
  run_smt("6593")
}

///|
test "3953" {
  run_smt("3953")
}

///|
test "2852" {
  run_smt("2852")
}

///|
test "t113" {
  run_smt("t113")
}

///|
test "fp-to_fp-10" {
  run_smt("fp-to_fp-10")
}

///|
test "t137" {
  run_smt("t137")
}

///|
test "3811" {
  run_smt("3811")
}

///|
test "issue-1366" {
  run_smt("issue-1366")
}

///|
test "fp-conversions-37" {
  run_smt("fp-conversions-37")
}

///|
test "5911" {
  run_smt("5911")
}

///|
test "fp-to_ubv-19" {
  run_smt("fp-to_ubv-19")
}

///|
test "cosine3" {
  run_smt("cosine3")
}

///|
test "3910" {
  run_smt("3910")
}

///|
test "purify_arith" {
  run_smt("purify_arith")
}

///|
test "3715" {
  run_smt("3715")
}

///|
test "4018" {
  run_smt("4018")
}

///|
test "fp-conversions-12" {
  run_smt("fp-conversions-12")
}

///|
test "trig-intersection" {
  run_smt("trig-intersection")
}

///|
test "t121" {
  run_smt("t121")
}

///|
test "core" {
  run_smt("core")
}

///|
test "3042" {
  run_smt("3042")
}

///|
test "fp-rem-12" {
  run_smt("fp-rem-12")
}

///|
test "t198" {
  run_smt("t198")
}

///|
test "fp-conversions-2" {
  run_smt("fp-conversions-2")
}

///|
test "3865" {
  run_smt("3865")
}

///|
test "fp-conversions-30" {
  run_smt("fp-conversions-30")
}

///|
test "issue-1645" {
  run_smt("issue-1645")
}

///|
test "3327" {
  run_smt("3327")
}

///|
test "fp-to_ubv-3" {
  run_smt("fp-to_ubv-3")
}

///|
test "arith_bug3" {
  run_smt("arith_bug3")
}

///|
test "dt_ayrat_2" {
  run_smt("dt_ayrat_2")
}

///|
test "fp-add-1" {
  run_smt("fp-add-1")
}

///|
test "fp-conversions-13" {
  run_smt("fp-conversions-13")
}

///|
test "fp-sqrt-9" {
  run_smt("fp-sqrt-9")
}

///|
test "fp-to_fp_unsigned-9" {
  run_smt("fp-to_fp_unsigned-9")
}

///|
test "3319" {
  run_smt("3319")
}

///|
test "3574" {
  run_smt("3574")
}

///|
test "3518" {
  run_smt("3518")
}

///|
test "2566" {
  run_smt("2566")
}

///|
test "fp-to_ubv-13" {
  run_smt("fp-to_ubv-13")
}

///|
test "3246" {
  run_smt("3246")
}

///|
test "fp-rem-tests-double-non-partial" {
  run_smt("fp-rem-tests-double-non-partial")
}

///|
test "3644" {
  run_smt("3644")
}

///|
test "3550" {
  run_smt("3550")
}

///|
test "3842" {
  run_smt("3842")
}

///|
test "nl52" {
  run_smt("nl52")
}

///|
test "t136" {
  run_smt("t136")
}

///|
test "2921" {
  run_smt("2921")
}

///|
test "fp-rem-4" {
  run_smt("fp-rem-4")
}

///|
test "3548" {
  run_smt("3548")
}

///|
test "pat3" {
  run_smt("pat3")
}

///|
test "nl23" {
  run_smt("nl23")
}

///|
test "t200" {
  run_smt("t200")
}

///|
test "strategy-par-or-2" {
  run_smt("strategy-par-or-2")
}

///|
test "fp-rem-15" {
  run_smt("fp-rem-15")
}

///|
test "nl46" {
  run_smt("nl46")
}

///|
test "fp-conversions-22" {
  run_smt("fp-conversions-22")
}

///|
test "fp-to_ubv-28" {
  run_smt("fp-to_ubv-28")
}

///|
test "3728" {
  run_smt("3728")
}

///|
test "2456" {
  run_smt("2456")
}

///|
test "2938" {
  run_smt("2938")
}

///|
test "3029" {
  run_smt("3029")
}

///|
test "with" {
  run_smt("with")
}

///|
test "2908" {
  run_smt("2908")
}

///|
test "6319" {
  run_smt("6319")
}

///|
test "issue-3225" {
  run_smt("issue-3225")
}

///|
test "3116" {
  run_smt("3116")
}

///|
test "2450" {
  run_smt("2450")
}

///|
test "t101" {
  run_smt("t101")
}

///|
test "nl11" {
  run_smt("nl11")
}

///|
test "o2" {
  run_smt("o2")
}

///|
test "issue-1655" {
  run_smt("issue-1655")
}

///|
test "t219" {
  run_smt("t219")
}

///|
test "dt_ayrat_1" {
  run_smt("dt_ayrat_1")
}

///|
test "3396" {
  run_smt("3396")
}

///|
test "fp-to_sbv-8" {
  run_smt("fp-to_sbv-8")
}

///|
test "5724" {
  run_smt("5724")
}

///|
test "3104" {
  run_smt("3104")
}

///|
test "issue-3023" {
  run_smt("issue-3023")
}

///|
test "lia2" {
  run_smt("lia2")
}

///|
test "incsat" {
  run_smt("incsat")
}

///|
test "string-concat" {
  run_smt("string-concat")
}

///|
test "6117-7" {
  run_smt("6117-7")
}

///|
test "fp-conversions-36" {
  run_smt("fp-conversions-36")
}

///|
test "fp-rem-1" {
  run_smt("fp-rem-1")
}

///|
test "fp-to_ieee_bv-1" {
  run_smt("fp-to_ieee_bv-1")
}

///|
test "fp-to_ubv-1" {
  run_smt("fp-to_ubv-1")
}

///|
test "nl55" {
  run_smt("nl55")
}

///|
test "3972" {
  run_smt("3972")
}

///|
test "3384" {
  run_smt("3384")
}

///|
test "3503" {
  run_smt("3503")
}

///|
test "fp-rounding_mode-1" {
  run_smt("fp-rounding_mode-1")
}

///|
test "3632" {
  run_smt("3632")
}

///|
test "fp-quantifiers-1" {
  run_smt("fp-quantifiers-1")
}

///|
test "fp-to_fp-6" {
  run_smt("fp-to_fp-6")
}

///|
test "fp-fma-10" {
  run_smt("fp-fma-10")
}

///|
test "3930" {
  run_smt("3930")
}

///|
test "6079-8" {
  run_smt("6079-8")
}

///|
test "small-bv-quant-1" {
  run_smt("small-bv-quant-1")
}

///|
test "fp-conversions-16" {
  run_smt("fp-conversions-16")
}

///|
test "t138" {
  run_smt("t138")
}

///|
test "fp-to_fp_unsigned-6" {
  run_smt("fp-to_fp_unsigned-6")
}

///|
test "t9" {
  run_smt("t9")
}

///|
test "nl3" {
  run_smt("nl3")
}

///|
test "6674-simp" {
  run_smt("6674-simp")
}

///|
test "t173" {
  run_smt("t173")
}

///|
test "3849" {
  run_smt("3849")
}

///|
test "nl26" {
  run_smt("nl26")
}

///|
test "2962" {
  run_smt("2962")
}

///|
test "4841-2" {
  run_smt("4841-2")
}

///|
test "z3.16" {
  run_smt("z3.16")
}

///|
test "t176" {
  run_smt("t176")
}

///|
test "fp-conversions-39" {
  run_smt("fp-conversions-39")
}

///|
test "o1" {
  run_smt("o1")
}

///|
test "nl43" {
  run_smt("nl43")
}

///|
test "string12" {
  run_smt("string12")
}

///|
test "3570" {
  run_smt("3570")
}

///|
test "3369" {
  run_smt("3369")
}

///|
test "fp-conversions-25" {
  run_smt("fp-conversions-25")
}

///|
test "3553" {
  run_smt("3553")
}

///|
test "3689" {
  run_smt("3689")
}

///|
test "fp-conversions-3" {
  run_smt("fp-conversions-3")
}

///|
test "fp-to_fp-9" {
  run_smt("fp-to_fp-9")
}

///|
test "z3.15" {
  run_smt("z3.15")
}

///|
test "cosine5" {
  run_smt("cosine5")
}

///|
test "issue-3028" {
  run_smt("issue-3028")
}

///|
test "fp-sqrt-4" {
  run_smt("fp-sqrt-4")
}

///|
test "3970" {
  run_smt("3970")
}

///|
test "fp-sqrt-7" {
  run_smt("fp-sqrt-7")
}

///|
test "fp-to_sbv-16" {
  run_smt("fp-to_sbv-16")
}

///|
test "eq" {
  run_smt("eq")
}

///|
test "mev_array" {
  run_smt("mev_array")
}

///|
test "3500" {
  run_smt("3500")
}

///|
test "string6" {
  run_smt("string6")
}

///|
test "2531" {
  run_smt("2531")
}

///|
test "t205" {
  run_smt("t205")
}

///|
test "nl27" {
  run_smt("nl27")
}

///|
test "2420" {
  run_smt("2420")
}

///|
test "nl51" {
  run_smt("nl51")
}

///|
test "3210" {
  run_smt("3210")
}

///|
test "nl40" {
  run_smt("nl40")
}

///|
test "3886" {
  run_smt("3886")
}

///|
test "nira" {
  run_smt("nira")
}

///|
test "fp-sqrt-3" {
  run_smt("fp-sqrt-3")
}

///|
test "t146" {
  run_smt("t146")
}

///|
test "fp-to_fp_real-2" {
  run_smt("fp-to_fp_real-2")
}

///|
test "nl1" {
  run_smt("nl1")
}

///|
test "fp-roundToIntegral-2" {
  run_smt("fp-roundToIntegral-2")
}

///|
test "nl34" {
  run_smt("nl34")
}

///|
test "t199" {
  run_smt("t199")
}

///|
test "fp-uf-7" {
  run_smt("fp-uf-7")
}

///|
test "t191" {
  run_smt("t191")
}

///|
test "3986" {
  run_smt("3986")
}

///|
test "t178" {
  run_smt("t178")
}

///|
test "2548" {
  run_smt("2548")
}

///|
test "6117-8" {
  run_smt("6117-8")
}

///|
test "2902" {
  run_smt("2902")
}

///|
test "3514" {
  run_smt("3514")
}

///|
test "string-ops" {
  run_smt("string-ops")
}

///|
test "t133" {
  run_smt("t133")
}

///|
test "z3.41" {
  run_smt("z3.41")
}

///|
test "3633" {
  run_smt("3633")
}

///|
test "3675" {
  run_smt("3675")
}

///|
test "3275" {
  run_smt("3275")
}

///|
test "1846" {
  run_smt("1846")
}

///|
test "t184" {
  run_smt("t184")
}

///|
test "t196" {
  run_smt("t196")
}

///|
test "3547" {
  run_smt("3547")
}

///|
test "fp-conversions-29" {
  run_smt("fp-conversions-29")
}

///|
test "4004" {
  run_smt("4004")
}

///|
test "t206" {
  run_smt("t206")
}

///|
test "2561" {
  run_smt("2561")
}

///|
test "nl18" {
  run_smt("nl18")
}

///|
test "z3.39" {
  run_smt("z3.39")
}

///|
test "6670" {
  run_smt("6670")
}

///|
test "fp-fma-20" {
  run_smt("fp-fma-20")
}

///|
test "t172" {
  run_smt("t172")
}

///|
test "5731" {
  run_smt("5731")
}

///|
test "fp-to_sbv-10" {
  run_smt("fp-to_sbv-10")
}

///|
test "t123" {
  run_smt("t123")
}

///|
test "2960" {
  run_smt("2960")
}

///|
test "nl58" {
  run_smt("nl58")
}

///|
test "3625" {
  run_smt("3625")
}

///|
test "2923" {
  run_smt("2923")
}

///|
test "nl7" {
  run_smt("nl7")
}

///|
test "t212" {
  run_smt("t212")
}

///|
test "fp-to_sbv-9" {
  run_smt("fp-to_sbv-9")
}

///|
test "3971" {
  run_smt("3971")
}

///|
test "sine8" {
  run_smt("sine8")
}

///|
test "3118" {
  run_smt("3118")
}

///|
test "3523" {
  run_smt("3523")
}

///|
test "fp-to_ubv-18" {
  run_smt("fp-to_ubv-18")
}

///|
test "strategy-default" {
  run_smt("strategy-default")
}

///|
test "testmapi" {
  run_smt("testmapi")
}

///|
test "string11" {
  run_smt("string11")
}

///|
test "string14" {
  run_smt("string14")
}

///|
test "fp-conversions-27" {
  run_smt("fp-conversions-27")
}

///|
test "6196" {
  run_smt("6196")
}

///|
test "pb" {
  run_smt("pb")
}

///|
test "3155" {
  run_smt("3155")
}

///|
test "3225" {
  run_smt("3225")
}

///|
test "3997" {
  run_smt("3997")
}

///|
test "fp-to_ubv-21" {
  run_smt("fp-to_ubv-21")
}

///|
test "fp-model_evaluator_1" {
  run_smt("fp-model_evaluator_1")
}

///|
test "fp-array-7" {
  run_smt("fp-array-7")
}

///|
test "nl31" {
  run_smt("nl31")
}

///|
test "3234" {
  run_smt("3234")
}

///|
test "fp-to_ubv-12" {
  run_smt("fp-to_ubv-12")
}

///|
test "fp-mul-1" {
  run_smt("fp-mul-1")
}

///|
test "3680" {
  run_smt("3680")
}

///|
test "segfault2" {
  run_smt("segfault2")
}

///|
test "3999" {
  run_smt("3999")
}

///|
test "t119" {
  run_smt("t119")
}

///|
test "3733" {
  run_smt("3733")
}

///|
test "fp-abs-2" {
  run_smt("fp-abs-2")
}

///|
test "cosine2" {
  run_smt("cosine2")
}

///|
test "3477" {
  run_smt("3477")
}

///|
test "3344" {
  run_smt("3344")
}

///|
test "blinking_query" {
  run_smt("blinking_query")
}

///|
test "sine" {
  run_smt("sine")
}

///|
test "3748" {
  run_smt("3748")
}

///|
test "div" {
  run_smt("div")
}

///|
test "3163" {
  run_smt("3163")
}

///|
test "3937" {
  run_smt("3937")
}

///|
test "3010" {
  run_smt("3010")
}

///|
test "4009" {
  run_smt("4009")
}

///|
test "fp-to_fp_unsigned-4" {
  run_smt("fp-to_fp_unsigned-4")
}

///|
test "5798" {
  run_smt("5798")
}

///|
test "fp-to_ubv-15" {
  run_smt("fp-to_ubv-15")
}

///|
test "3379" {
  run_smt("3379")
}

///|
test "fp-to_fp-7" {
  run_smt("fp-to_fp-7")
}

///|
test "3417" {
  run_smt("3417")
}

///|
test "3075" {
  run_smt("3075")
}

///|
test "6117-1" {
  run_smt("6117-1")
}

///|
test "consequences" {
  run_smt("consequences")
}

///|
test "crash" {
  run_smt("crash")
}

///|
test "issue-1566" {
  run_smt("issue-1566")
}

///|
test "dt2bv" {
  run_smt("dt2bv")
}

///|
test "4019" {
  run_smt("4019")
}

///|
test "3221" {
  run_smt("3221")
}

///|
test "fp-roundToIntegral-4" {
  run_smt("fp-roundToIntegral-4")
}

///|
test "fp-uf-4" {
  run_smt("fp-uf-4")
}

///|
test "fp-sqrt-8" {
  run_smt("fp-sqrt-8")
}

///|
test "nl4" {
  run_smt("nl4")
}

///|
test "3665" {
  run_smt("3665")
}

///|
test "2879" {
  run_smt("2879")
}

///|
test "t1" {
  run_smt("t1")
}

///|
test "3223" {
  run_smt("3223")
}

///|
test "3587" {
  run_smt("3587")
}

///|
test "6116" {
  run_smt("6116")
}

///|
test "3438" {
  run_smt("3438")
}

///|
test "issue-1538" {
  run_smt("issue-1538")
}

///|
test "fp-neg" {
  run_smt("fp-neg")
}

///|
test "3827" {
  run_smt("3827")
}

///|
test "nl29" {
  run_smt("nl29")
}

///|
test "3260" {
  run_smt("3260")
}

///|
test "fp-roundToIntegral-5" {
  run_smt("fp-roundToIntegral-5")
}

///|
test "fp-sub-1" {
  run_smt("fp-sub-1")
}

///|
test "fp-rem-13-3" {
  run_smt("fp-rem-13-3")
}

///|
test "fp-fma-3" {
  run_smt("fp-fma-3")
}

///|
test "o4" {
  run_smt("o4")
}

///|
test "3153" {
  run_smt("3153")
}

///|
test "tan3" {
  run_smt("tan3")
}

///|
test "updt" {
  run_smt("updt")
}

///|
test "fp-mul-2" {
  run_smt("fp-mul-2")
}

///|
test "cosine" {
  run_smt("cosine")
}

///|
test "fp-rem-13-4" {
  run_smt("fp-rem-13-4")
}

///|
test "fp-rem-13-2" {
  run_smt("fp-rem-13-2")
}

///|
test "z3name_bug" {
  run_smt("z3name_bug")
}

///|
test "macro-finder-cores" {
  run_smt("macro-finder-cores")
}

///|
test "3775" {
  run_smt("3775")
}

///|
test "3277" {
  run_smt("3277")
}

///|
test "fp-conversions-38" {
  run_smt("fp-conversions-38")
}

///|
test "fp-to_fp_unsigned-12" {
  run_smt("fp-to_fp_unsigned-12")
}

///|
test "3106" {
  run_smt("3106")
}

///|
test "4008" {
  run_smt("4008")
}

///|
test "t143" {
  run_smt("t143")
}

///|
test "3591" {
  run_smt("3591")
}

///|
test "t132" {
  run_smt("t132")
}

///|
test "2432" {
  run_smt("2432")
}

///|
test "sine2" {
  run_smt("sine2")
}

///|
test "nl45" {
  run_smt("nl45")
}

///|
test "2868" {
  run_smt("2868")
}

///|
test "fp-to_sbv-12" {
  run_smt("fp-to_sbv-12")
}

///|
test "nl24" {
  run_smt("nl24")
}

///|
test "fp-to_ubv-22" {
  run_smt("fp-to_ubv-22")
}

///|
test "5728" {
  run_smt("5728")
}

///|
test "fp-min-zero-zero-5" {
  run_smt("fp-min-zero-zero-5")
}

///|
test "3100" {
  run_smt("3100")
}

///|
test "t124" {
  run_smt("t124")
}

///|
test "bvsmod" {
  run_smt("bvsmod")
}

///|
test "nl48" {
  run_smt("nl48")
}

///|
test "fp-fma-18" {
  run_smt("fp-fma-18")
}

///|
test "fp-to_ubv-30" {
  run_smt("fp-to_ubv-30")
}

///|
test "3218" {
  run_smt("3218")
}

///|
test "fp-to_sbv-3" {
  run_smt("fp-to_sbv-3")
}

///|
test "fp-conversions-19" {
  run_smt("fp-conversions-19")
}

///|
test "fp-rounding_mode-2" {
  run_smt("fp-rounding_mode-2")
}

///|
test "3391" {
  run_smt("3391")
}

///|
test "2890" {
  run_smt("2890")
}

///|
test "z3.40" {
  run_smt("z3.40")
}

///|
test "nl2" {
  run_smt("nl2")
}

///|
test "3312" {
  run_smt("3312")
}

///|
test "5721" {
  run_smt("5721")
}

///|
test "3889" {
  run_smt("3889")
}

///|
test "fp-div-2" {
  run_smt("fp-div-2")
}

///|
test "3342" {
  run_smt("3342")
}

///|
test "nl32" {
  run_smt("nl32")
}

///|
test "fp-to_fp-signed-1" {
  run_smt("fp-to_fp-signed-1")
}

///|
test "fp-conversions-26" {
  run_smt("fp-conversions-26")
}

///|
test "4017" {
  run_smt("4017")
}

///|
test "fp-min-zero-zero-3" {
  run_smt("fp-min-zero-zero-3")
}

///|
test "fp-to_fp-1" {
  run_smt("fp-to_fp-1")
}

///|
test "fp-rounding_mode-3" {
  run_smt("fp-rounding_mode-3")
}

///|
test "nl30" {
  run_smt("nl30")
}

///|
test "z3.17" {
  run_smt("z3.17")
}

///|
test "3834" {
  run_smt("3834")
}

///|
test "fp-roundToIntegral-8" {
  run_smt("fp-roundToIntegral-8")
}

///|
test "fp-to_sbv-15" {
  run_smt("fp-to_sbv-15")
}

///|
test "3301" {
  run_smt("3301")
}

///|
test "nl12" {
  run_smt("nl12")
}

///|
test "fp-conversions-10" {
  run_smt("fp-conversions-10")
}

///|
test "fp-to_ubv-14" {
  run_smt("fp-to_ubv-14")
}

///|
test "3282" {
  run_smt("3282")
}

///|
test "fp-to_fp_unsigned-13" {
  run_smt("fp-to_fp_unsigned-13")
}

///|
test "3504" {
  run_smt("3504")
}

///|
test "z3.5" {
  run_smt("z3.5")
}

///|
test "t211" {
  run_smt("t211")
}

///|
test "nl49" {
  run_smt("nl49")
}

///|
test "fp-min-zero-zero-1" {
  run_smt("fp-min-zero-zero-1")
}

///|
test "z3.34" {
  run_smt("z3.34")
}

///|
test "fp-to_sbv-7" {
  run_smt("fp-to_sbv-7")
}

///|
test "t175" {
  run_smt("t175")
}

///|
test "fp-conversions-34" {
  run_smt("fp-conversions-34")
}

///|
test "3521" {
  run_smt("3521")
}

///|
test "3688" {
  run_smt("3688")
}

///|
test "root-pre" {
  run_smt("root-pre")
}

///|
test "2417" {
  run_smt("2417")
}

///|
test "6553-2-simp" {
  run_smt("6553-2-simp")
}

///|
test "3383" {
  run_smt("3383")
}

///|
test "nl56" {
  run_smt("nl56")
}

///|
test "fp-predicates" {
  run_smt("fp-predicates")
}

///|
test "3524" {
  run_smt("3524")
}

///|
test "t213" {
  run_smt("t213")
}

///|
test "fp-conversions-7" {
  run_smt("fp-conversions-7")
}

///|
test "3241" {
  run_smt("3241")
}

///|
test "model_compact_bug" {
  run_smt("model_compact_bug")
}

///|
test "tan" {
  run_smt("tan")
}

///|
test "3123" {
  run_smt("3123")
}

///|
test "3247" {
  run_smt("3247")
}

///|
test "t139" {
  run_smt("t139")
}

///|
test "3973" {
  run_smt("3973")
}

///|
test "3601" {
  run_smt("3601")
}

///|
test "3752" {
  run_smt("3752")
}

///|
test "fp-datatype_with_float-3" {
  run_smt("fp-datatype_with_float-3")
}

///|
test "sine7" {
  run_smt("sine7")
}

///|
test "fp-rem-9" {
  run_smt("fp-rem-9")
}

///|
test "2856" {
  run_smt("2856")
}

///|
test "2560" {
  run_smt("2560")
}

///|
test "t112" {
  run_smt("t112")
}

///|
test "3917" {
  run_smt("3917")
}

///|
test "fp-uf-8" {
  run_smt("fp-uf-8")
}

///|
test "fp-conversions-14" {
  run_smt("fp-conversions-14")
}

///|
test "6117-6" {
  run_smt("6117-6")
}

///|
test "nl10" {
  run_smt("nl10")
}

///|
test "fp-to_ubv-27" {
  run_smt("fp-to_ubv-27")
}

///|
test "nl47" {
  run_smt("nl47")
}

///|
test "t189" {
  run_smt("t189")
}

///|
test "fp-conversions-20" {
  run_smt("fp-conversions-20")
}

///|
test "fp-to_fp-3" {
  run_smt("fp-to_fp-3")
}

///|
test "fp-conversions-6" {
  run_smt("fp-conversions-6")
}

///|
test "z3.30" {
  run_smt("z3.30")
}

///|
test "z3.20" {
  run_smt("z3.20")
}

///|
test "2530" {
  run_smt("2530")
}

///|
test "z3.43" {
  run_smt("z3.43")
}

///|
test "6117-4" {
  run_smt("6117-4")
}

///|
test "fp-to_ubv-11" {
  run_smt("fp-to_ubv-11")
}

///|
test "4032" {
  run_smt("4032")
}

///|
test "3226" {
  run_smt("3226")
}

///|
test "6052" {
  run_smt("6052")
}

///|
test "fp-rem-13-1" {
  run_smt("fp-rem-13-1")
}

///|
test "qffp-quant" {
  run_smt("qffp-quant")
}

///|
test "issue-3038" {
  run_smt("issue-3038")
}

///|
test "3529" {
  run_smt("3529")
}

///|
test "3115" {
  run_smt("3115")
}

///|
test "fp-to_ubv-2" {
  run_smt("fp-to_ubv-2")
}

///|
test "fp-max-zero-zero-3" {
  run_smt("fp-max-zero-zero-3")
}

///|
test "3626" {
  run_smt("3626")
}

///|
test "fp-conversions-32" {
  run_smt("fp-conversions-32")
}

///|
test "3458" {
  run_smt("3458")
}

///|
test "fp-conversions-18" {
  run_smt("fp-conversions-18")
}

///|
test "4021" {
  run_smt("4021")
}

///|
test "issue-963" {
  run_smt("issue-963")
}

///|
test "fp-rem-tests-double-partial" {
  run_smt("fp-rem-tests-double-partial")
}

///|
test "3538" {
  run_smt("3538")
}

///|
test "sine3" {
  run_smt("sine3")
}

///|
test "3434" {
  run_smt("3434")
}

///|
test "3339" {
  run_smt("3339")
}

///|
test "re_rewriter" {
  run_smt("re_rewriter")
}

///|
test "fp-conversions-28" {
  run_smt("fp-conversions-28")
}

///|
test "6079-1-simp" {
  run_smt("6079-1-simp")
}

///|
test "core2" {
  run_smt("core2")
}

///|
test "sub" {
  run_smt("sub")
}

///|
test "fp-fma-14" {
  run_smt("fp-fma-14")
}

///|
test "6079-8-simp" {
  run_smt("6079-8-simp")
}

///|
test "t125" {
  run_smt("t125")
}

///|
test "fp-to_sbv-4" {
  run_smt("fp-to_sbv-4")
}

///|
test "3759" {
  run_smt("3759")
}

///|
test "o6" {
  run_smt("o6")
}

///|
test "o5" {
  run_smt("o5")
}

///|
test "2990" {
  run_smt("2990")
}

///|
test "z3.31" {
  run_smt("z3.31")
}

///|
test "z3.37" {
  run_smt("z3.37")
}

///|
test "t158" {
  run_smt("t158")
}

///|
test "fp-quantifiers-2" {
  run_smt("fp-quantifiers-2")
}

///|
test "sqrt-bug" {
  run_smt("sqrt-bug")
}

///|
test "fp-to_fp_real-1" {
  run_smt("fp-to_fp_real-1")
}

///|
test "ule" {
  run_smt("ule")
}

///|
test "3749" {
  run_smt("3749")
}

///|
test "t109" {
  run_smt("t109")
}

///|
test "nl25" {
  run_smt("nl25")
}

///|
test "7489" {
  run_smt("7489")
}

///|
test "trig-bounds" {
  run_smt("trig-bounds")
}

///|
test "issue-1086" {
  run_smt("issue-1086")
}

///|
test "t209" {
  run_smt("t209")
}

///|
test "2924" {
  run_smt("2924")
}

///|
test "3896" {
  run_smt("3896")
}

///|
test "nl37" {
  run_smt("nl37")
}

///|
test "3127" {
  run_smt("3127")
}

///|
test "fp-to_sbv-6" {
  run_smt("fp-to_sbv-6")
}

///|
test "t193" {
  run_smt("t193")
}

///|
test "fp-array-6" {
  run_smt("fp-array-6")
}

///|
test "issue-1733" {
  run_smt("issue-1733")
}

///|
test "z3.29" {
  run_smt("z3.29")
}

///|
test "3555" {
  run_smt("3555")
}

///|
test "t207" {
  run_smt("t207")
}

///|
test "3440" {
  run_smt("3440")
}

///|
test "fp-to_fp_unsigned-1" {
  run_smt("fp-to_fp_unsigned-1")
}

///|
test "abs" {
  run_smt("abs")
}

///|
test "z3.4" {
  run_smt("z3.4")
}

///|
test "t197" {
  run_smt("t197")
}

///|
test "trig-spherical" {
  run_smt("trig-spherical")
}

///|
test "fp-fma-13" {
  run_smt("fp-fma-13")
}

///|
test "bvcore" {
  run_smt("bvcore")
}

///|
test "4041" {
  run_smt("4041")
}

///|
test "3141" {
  run_smt("3141")
}

///|
test "fp-to_ubv-20" {
  run_smt("fp-to_ubv-20")
}

///|
test "3190" {
  run_smt("3190")
}

///|
test "t145" {
  run_smt("t145")
}

///|
test "t169" {
  run_smt("t169")
}

///|
test "cosine4" {
  run_smt("cosine4")
}

///|
test "string13" {
  run_smt("string13")
}

///|
test "t174" {
  run_smt("t174")
}

///|
test "sine6" {
  run_smt("sine6")
}

///|
test "z3.38" {
  run_smt("z3.38")
}

///|
test "fp-rem-tests-single-non-partial" {
  run_smt("fp-rem-tests-single-non-partial")
}

///|
test "power-zero-safe" {
  run_smt("power-zero-safe")
}

///|
test "3517" {
  run_smt("3517")
}

///|
test "atan" {
  run_smt("atan")
}

///|
test "6336" {
  run_smt("6336")
}

///|
test "627" {
  run_smt("627")
}

///|
test "issue-1218" {
  run_smt("issue-1218")
}

///|
test "segfaults2_minimal" {
  run_smt("segfaults2_minimal")
}

///|
test "fp-fp-1" {
  run_smt("fp-fp-1")
}

///|
test "3237" {
  run_smt("3237")
}

///|
test "3081" {
  run_smt("3081")
}

///|
test "fp-to_fp-4" {
  run_smt("fp-to_fp-4")
}

///|
test "3934" {
  run_smt("3934")
}

///|
test "issue-1846" {
  run_smt("issue-1846")
}

///|
test "issue-1092" {
  run_smt("issue-1092")
}

///|
test "t181" {
  run_smt("t181")
}

///|
test "4841-simp" {
  run_smt("4841-simp")
}

///|
test "nl59" {
  run_smt("nl59")
}

///|
test "t114" {
  run_smt("t114")
}

///|
test "fp-uf-2" {
  run_smt("fp-uf-2")
}

///|
test "t180" {
  run_smt("t180")
}

///|
test "fp-conversions-31" {
  run_smt("fp-conversions-31")
}

///|
test "attr_bug" {
  run_smt("attr_bug")
}

///|
test "nl35" {
  run_smt("nl35")
}

///|
test "nl50" {
  run_smt("nl50")
}

///|
test "issue-1694" {
  run_smt("issue-1694")
}

///|
test "3332" {
  run_smt("3332")
}

///|
test "3785" {
  run_smt("3785")
}

///|
test "string3" {
  run_smt("string3")
}

///|
test "fp-div-3" {
  run_smt("fp-div-3")
}

///|
test "fp-array-4" {
  run_smt("fp-array-4")
}

///|
test "fp-conversions-41" {
  run_smt("fp-conversions-41")
}

///|
test "fp-rem-11" {
  run_smt("fp-rem-11")
}

///|
test "8099" {
  run_smt("8099")
}

///|
test "t208" {
  run_smt("t208")
}

///|
test "fp-pzero" {
  run_smt("fp-pzero")
}

///|
test "2520" {
  run_smt("2520")
}

///|
test "t131" {
  run_smt("t131")
}

///|
test "bv0" {
  run_smt("bv0")
}

///|
test "qfbv-quant" {
  run_smt("qfbv-quant")
}

///|
test "t102" {
  run_smt("t102")
}

///|
test "3549" {
  run_smt("3549")
}

///|
test "3286" {
  run_smt("3286")
}

///|
test "t195" {
  run_smt("t195")
}

///|
test "t11" {
  run_smt("t11")
}

///|
test "fp-to_sbv-2" {
  run_smt("fp-to_sbv-2")
}

///|
test "fp-array-2" {
  run_smt("fp-array-2")
}

///|
test "fp-to_ubv-25" {
  run_smt("fp-to_ubv-25")
}

///|
test "fp-fma-11" {
  run_smt("fp-fma-11")
}

///|
test "mbqi_bug" {
  run_smt("mbqi_bug")
}

///|
test "3672" {
  run_smt("3672")
}

///|
test "issue-1224" {
  run_smt("issue-1224")
}

///|
test "issue-1677" {
  run_smt("issue-1677")
}

///|
test "3960" {
  run_smt("3960")
}

///|
test "t215" {
  run_smt("t215")
}

///|
test "3607" {
  run_smt("3607")
}

///|
test "fp-model_evaluator_6" {
  run_smt("fp-model_evaluator_6")
}

///|
test "string9" {
  run_smt("string9")
}

///|
test "issue-790" {
  run_smt("issue-790")
}

///|
test "3473" {
  run_smt("3473")
}

///|
test "fp-ninf" {
  run_smt("fp-ninf")
}

///|
test "issue-1729" {
  run_smt("issue-1729")
}

///|
test "3502" {
  run_smt("3502")
}

///|
test "fp-to_fp_unsigned-5" {
  run_smt("fp-to_fp_unsigned-5")
}

///|
test "3967" {
  run_smt("3967")
}

///|
test "3754" {
  run_smt("3754")
}

///|
test "nl15" {
  run_smt("nl15")
}

///|
test "3249" {
  run_smt("3249")
}

///|
test "fp-min-zero-zero-2" {
  run_smt("fp-min-zero-zero-2")
}

///|
test "fp-to_ubv-6" {
  run_smt("fp-to_ubv-6")
}

///|
test "t185" {
  run_smt("t185")
}

///|
test "t104" {
  run_smt("t104")
}

///|
test "issue-1683" {
  run_smt("issue-1683")
}

///|
test "2447" {
  run_smt("2447")
}

///|
test "fp-add-sub" {
  run_smt("fp-add-sub")
}

///|
test "t160" {
  run_smt("t160")
}

///|
test "mul" {
  run_smt("mul")
}

///|
test "fp-model_evaluator_7" {
  run_smt("fp-model_evaluator_7")
}

///|
test "nl13" {
  run_smt("nl13")
}

///|
test "3105" {
  run_smt("3105")
}

///|
test "fp-to_fp-11" {
  run_smt("fp-to_fp-11")
}

///|
test "fp-to_ubv-24" {
  run_smt("fp-to_ubv-24")
}

///|
test "fp-conversions-23" {
  run_smt("fp-conversions-23")
}

///|
test "3559" {
  run_smt("3559")
}

///|
test "fp-nzero" {
  run_smt("fp-nzero")
}

///|
test "array" {
  run_smt("array")
}

///|
test "2912" {
  run_smt("2912")
}

///|
test "cosine6" {
  run_smt("cosine6")
}

///|
test "3573" {
  run_smt("3573")
}

///|
test "fp-to_fp-5" {
  run_smt("fp-to_fp-5")
}

///|
test "2891" {
  run_smt("2891")
}

///|
test "fp-to_fp_unsigned-11" {
  run_smt("fp-to_fp_unsigned-11")
}

///|
test "testmap" {
  run_smt("testmap")
}

///|
test "t115" {
  run_smt("t115")
}

///|
test "fp-rem-3" {
  run_smt("fp-rem-3")
}

///|
test "fp-rem-14" {
  run_smt("fp-rem-14")
}

///|
test "2937" {
  run_smt("2937")
}

///|
test "token3" {
  run_smt("token3")
}

///|
test "3576" {
  run_smt("3576")
}

///|
test "3436" {
  run_smt("3436")
}

///|
test "fp-roundToIntegral-3" {
  run_smt("fp-roundToIntegral-3")
}

///|
test "fp-conversions-9" {
  run_smt("fp-conversions-9")
}

///|
test "fp-rem-2" {
  run_smt("fp-rem-2")
}

///|
test "2889" {
  run_smt("2889")
}

///|
test "3572" {
  run_smt("3572")
}

///|
test "4841-1" {
  run_smt("4841-1")
}

///|
test "fp-conversions-24" {
  run_smt("fp-conversions-24")
}

///|
test "fp-to_fp_unsigned-3" {
  run_smt("fp-to_fp_unsigned-3")
}

///|
test "3799" {
  run_smt("3799")
}

///|
test "cosine7" {
  run_smt("cosine7")
}

///|
test "fp-conversions-33" {
  run_smt("fp-conversions-33")
}

///|
test "ho" {
  run_smt("ho")
}

///|
test "fp-rem-17" {
  run_smt("fp-rem-17")
}

///|
test "fp-div-1" {
  run_smt("fp-div-1")
}

///|
test "3111" {
  run_smt("3111")
}

///|
test "fp-sqrt-5" {
  run_smt("fp-sqrt-5")
}

///|
test "3411" {
  run_smt("3411")
}

///|
test "const_array_bug" {
  run_smt("const_array_bug")
}

///|
test "2892" {
  run_smt("2892")
}

///|
test "nl36" {
  run_smt("nl36")
}

///|
test "6728-1" {
  run_smt("6728-1")
}

///|
test "3255" {
  run_smt("3255")
}

///|
test "3751" {
  run_smt("3751")
}

///|
test "fp-rem-8" {
  run_smt("fp-rem-8")
}

///|
test "sine9" {
  run_smt("sine9")
}

///|
test "re" {
  run_smt("re")
}

///|
test "arith_bug2" {
  run_smt("arith_bug2")
}

///|
test "3125" {
  run_smt("3125")
}

///|
test "z3.28" {
  run_smt("z3.28")
}

///|
test "fp-max-zero-zero-1" {
  run_smt("fp-max-zero-zero-1")
}

///|
test "fp-to_sbv-5" {
  run_smt("fp-to_sbv-5")
}

///|
test "t217" {
  run_smt("t217")
}

///|
test "nl19" {
  run_smt("nl19")
}

///|
test "fp-to_fp_unsigned-10" {
  run_smt("fp-to_fp_unsigned-10")
}

///|
test "lia1" {
  run_smt("lia1")
}

///|
test "fp-model_evaluator_4" {
  run_smt("fp-model_evaluator_4")
}

///|
test "4003" {
  run_smt("4003")
}

///|
test "3709" {
  run_smt("3709")
}

///|
test "sine5" {
  run_smt("sine5")
}

///|
test "t16" {
  run_smt("t16")
}

///|
test "nl17" {
  run_smt("nl17")
}

///|
test "t117" {
  run_smt("t117")
}

///|
test "t171" {
  run_smt("t171")
}

///|
test "2533" {
  run_smt("2533")
}

///|
test "3006" {
  run_smt("3006")
}

///|
test "4010" {
  run_smt("4010")
}

///|
test "fp-to_fp_float-1" {
  run_smt("fp-to_fp_float-1")
}

///|
test "3569" {
  run_smt("3569")
}

///|
test "arith_bug" {
  run_smt("arith_bug")
}

///|
test "issue2301" {
  run_smt("issue2301")
}

///|
test "3267" {
  run_smt("3267")
}

///|
test "strategy-par-or-3" {
  run_smt("strategy-par-or-3")
}

///|
test "fp-conversions-35" {
  run_smt("fp-conversions-35")
}

///|
test "fp-nan" {
  run_smt("fp-nan")
}

///|
test "string-simplify" {
  run_smt("string-simplify")
}

///|
test "t111" {
  run_smt("t111")
}

///|
test "3303" {
  run_smt("3303")
}

///|
test "3252" {
  run_smt("3252")
}

///|
test "memset" {
  run_smt("memset")
}

///|
test "z3.2" {
  run_smt("z3.2")
}

///|
test "3532" {
  run_smt("3532")
}

///|
test "t210" {
  run_smt("t210")
}

///|
test "fp-fma-19" {
  run_smt("fp-fma-19")
}

///|
test "2919" {
  run_smt("2919")
}

///|
test "3148" {
  run_smt("3148")
}

///|
test "3209" {
  run_smt("3209")
}

///|
test "tan2" {
  run_smt("tan2")
}

///|
test "fp-fma-6" {
  run_smt("fp-fma-6")
}

///|
test "2935" {
  run_smt("2935")
}

///|
test "3028" {
  run_smt("3028")
}

///|
test "dt_ayrat_4" {
  run_smt("dt_ayrat_4")
}

///|
test "t154" {
  run_smt("t154")
}

///|
test "3705" {
  run_smt("3705")
}

///|
test "z3.53" {
  run_smt("z3.53")
}

///|
test "3113" {
  run_smt("3113")
}

///|
test "issue-1658" {
  run_smt("issue-1658")
}

///|
test "fp-conversions-11" {
  run_smt("fp-conversions-11")
}

///|
test "3294" {
  run_smt("3294")
}

///|
test "fp-fma-4" {
  run_smt("fp-fma-4")
}

///|
test "bad_set_logic" {
  run_smt("bad_set_logic")
}

///|
test "t214" {
  run_smt("t214")
}

///|
test "z3.1" {
  run_smt("z3.1")
}

///|
test "t190" {
  run_smt("t190")
}

///|
test "fp-model_evaluator_3" {
  run_smt("fp-model_evaluator_3")
}

///|
test "3335" {
  run_smt("3335")
}

///|
test "2838" {
  run_smt("2838")
}

///|
test "trig-quadrants" {
  run_smt("trig-quadrants")
}

///|
test "issue-3106" {
  run_smt("issue-3106")
}

///|
test "fp-min-zero-zero-4" {
  run_smt("fp-min-zero-zero-4")
}

///|
test "dt_ayrat_3" {
  run_smt("dt_ayrat_3")
}

///|
test "fp-fma-8" {
  run_smt("fp-fma-8")
}

///|
test "2556" {
  run_smt("2556")
}

///|
test "fp-uf-5" {
  run_smt("fp-uf-5")
}

///|
test "z3.14" {
  run_smt("z3.14")
}

///|
test "4033" {
  run_smt("4033")
}

///|
test "3336" {
  run_smt("3336")
}

///|
test "fp-mul-3" {
  run_smt("fp-mul-3")
}

///|
test "3933" {
  run_smt("3933")
}

///|
test "nl9" {
  run_smt("nl9")
}

///|
test "fp-fma-2" {
  run_smt("fp-fma-2")
}

///|
test "power" {
  run_smt("power")
}

///|
test "string-literals" {
  run_smt("string-literals")
}

///|
test "nl57" {
  run_smt("nl57")
}

///|
test "loop" {
  run_smt("loop")
}

///|
test "3385" {
  run_smt("3385")
}

///|
test "fp-datatype_with_float-2" {
  run_smt("fp-datatype_with_float-2")
}

///|
test "fp-conversions-17" {
  run_smt("fp-conversions-17")
}

///|
test "fp-roundToIntegral-6" {
  run_smt("fp-roundToIntegral-6")
}

///|
test "3220" {
  run_smt("3220")
}

///|
test "nl44" {
  run_smt("nl44")
}

///|
test "6079-4" {
  run_smt("6079-4")
}

///|
test "fp-lt-gt" {
  run_smt("fp-lt-gt")
}

///|
test "sine4" {
  run_smt("sine4")
}

///|
test "fp-fma-15" {
  run_smt("fp-fma-15")
}

///|
test "fp-conversions-21" {
  run_smt("fp-conversions-21")
}

///|
test "fp-model_evaluator_5" {
  run_smt("fp-model_evaluator_5")
}

///|
test "issue-1816" {
  run_smt("issue-1816")
}

///|
test "fp-to_ubv-16" {
  run_smt("fp-to_ubv-16")
}

///|
test "pat2" {
  run_smt("pat2")
}

///|
test "t135" {
  run_smt("t135")
}

///|
test "fp-rem-10" {
  run_smt("fp-rem-10")
}

///|
test "nl38" {
  run_smt("nl38")
}

///|
test "t168" {
  run_smt("t168")
}

///|
test "4044" {
  run_smt("4044")
}

///|
test "fp-to_fp-2" {
  run_smt("fp-to_fp-2")
}

///|
test "fp-rem-7" {
  run_smt("fp-rem-7")
}

///|
test "fp-max-zero-zero-2" {
  run_smt("fp-max-zero-zero-2")
}

///|
test "2478" {
  run_smt("2478")
}

///|
test "fp-div-4" {
  run_smt("fp-div-4")
}

///|
test "3642" {
  run_smt("3642")
}

///|
test "fp-sorts-1" {
  run_smt("fp-sorts-1")
}

///|
test "fp-fma-16" {
  run_smt("fp-fma-16")
}

///|
test "nl54" {
  run_smt("nl54")
}

///|
test "t148" {
  run_smt("t148")
}

///|
test "fp-to_sbv-1" {
  run_smt("fp-to_sbv-1")
}

///|
test "3984" {
  run_smt("3984")
}

///|
test "fp-conversions-40" {
  run_smt("fp-conversions-40")
}

///|
test "testfoldl" {
  run_smt("testfoldl")
}

///|
test "3742" {
  run_smt("3742")
}

///|
test "fp-to_ubv-9" {
  run_smt("fp-to_ubv-9")
}

///|
test "power-sqrt-unsafe" {
  run_smt("power-sqrt-unsafe")
}

///|
test "fp-rem-16" {
  run_smt("fp-rem-16")
}

///|
test "3324" {
  run_smt("3324")
}

///|
test "4013" {
  run_smt("4013")
}

///|
test "fp-to_fp_unsigned-8" {
  run_smt("fp-to_fp_unsigned-8")
}

///|
test "2943" {
  run_smt("2943")
}

///|
test "b1" {
  run_smt("b1")
}

///|
test "blinking_query2" {
  run_smt("blinking_query2")
}

///|
test "t134" {
  run_smt("t134")
}

///|
test "issue-1851" {
  run_smt("issue-1851")
}

///|
test "3919" {
  run_smt("3919")
}

///|
test "fp-conversions-5" {
  run_smt("fp-conversions-5")
}

///|
test "6054" {
  run_smt("6054")
}

///|
test "asin" {
  run_smt("asin")
}

///|
test "3959" {
  run_smt("3959")
}

///|
test "fp-to_fp_float-3" {
  run_smt("fp-to_fp_float-3")
}

///|
test "3700" {
  run_smt("3700")
}

///|
test "t8" {
  run_smt("t8")
}

///|
test "nl21" {
  run_smt("nl21")
}

///|
test "3137" {
  run_smt("3137")
}

///|
test "t201" {
  run_smt("t201")
}

///|
test "3735" {
  run_smt("3735")
}

///|
test "6902" {
  run_smt("6902")
}

///|
test "issue-1725" {
  run_smt("issue-1725")
}

///|
test "4015" {
  run_smt("4015")
}

///|
test "3663" {
  run_smt("3663")
}

///|
test "fp-feature-check-1" {
  run_smt("fp-feature-check-1")
}

///|
test "t150" {
  run_smt("t150")
}

///|
test "acos" {
  run_smt("acos")
}

///|
test "fp-fma-12" {
  run_smt("fp-fma-12")
}

///|
test "3832" {
  run_smt("3832")
}

///|
test "3816" {
  run_smt("3816")
}

///|
test "fp-model_evaluator_2" {
  run_smt("fp-model_evaluator_2")
}

///|
test "5075" {
  run_smt("5075")
}

///|
test "2883" {
  run_smt("2883")
}

///|
test "fp-to_ubv-8" {
  run_smt("fp-to_ubv-8")
}

///|
test "fp-to_ubv-4" {
  run_smt("fp-to_ubv-4")
}

///|
test "5693" {
  run_smt("5693")
}

///|
test "epsilon" {
  run_smt("epsilon")
}

///|
test "2567" {
  run_smt("2567")
}

///|
test "3765" {
  run_smt("3765")
}

///|
test "t192" {
  run_smt("t192")
}

///|
test "string-eval" {
  run_smt("string-eval")
}

///|
test "t216" {
  run_smt("t216")
}

///|
test "fp-to_ubv-26" {
  run_smt("fp-to_ubv-26")
}

///|
test "3253" {
  run_smt("3253")
}

///|
test "nl-simp" {
  run_smt("nl-simp")
}

///|
test "fp-array-3" {
  run_smt("fp-array-3")
}

///|
test "z3.12" {
  run_smt("z3.12")
}

///|
test "issue-628" {
  run_smt("issue-628")
}

///|
test "2877" {
  run_smt("2877")
}

///|
test "nl28" {
  run_smt("nl28")
}

///|
test "fp-abs-1" {
  run_smt("fp-abs-1")
}

///|
test "fp-fma-9" {
  run_smt("fp-fma-9")
}

///|
test "nl41" {
  run_smt("nl41")
}

///|
test "fp-to_sbv-14" {
  run_smt("fp-to_sbv-14")
}

///|
test "unsatcore" {
  run_smt("unsatcore")
}

///|
test "2955" {
  run_smt("2955")
}

///|
test "2415" {
  run_smt("2415")
}

///|
test "nl39" {
  run_smt("nl39")
}

///|
test "fp-operations" {
  run_smt("fp-operations")
}

///|
test "3422" {
  run_smt("3422")
}

///|
test "nl16" {
  run_smt("nl16")
}

///|
test "z3.6" {
  run_smt("z3.6")
}

///|
test "t151" {
  run_smt("t151")
}

///|
test "3825" {
  run_smt("3825")
}

///|
test "z3.52" {
  run_smt("z3.52")
}

///|
test "fp-to_sbv-11" {
  run_smt("fp-to_sbv-11")
}

///|
test "t122" {
  run_smt("t122")
}

///|
test "z3.26" {
  run_smt("z3.26")
}

///|
test "fp-fma-1" {
  run_smt("fp-fma-1")
}

///|
test "3423" {
  run_smt("3423")
}

///|
test "3732" {
  run_smt("3732")
}

///|
test "nl20" {
  run_smt("nl20")
}

///|
test "2573" {
  run_smt("2573")
}

///|
test "issue-2416-2" {
  run_smt("issue-2416-2")
}

///|
test "fp-rem-13" {
  run_smt("fp-rem-13")
}

///|
test "issue-1699" {
  run_smt("issue-1699")
}

///|
test "t194" {
  run_smt("t194")
}

///|
test "3968" {
  run_smt("3968")
}

///|
test "fp-fma-5" {
  run_smt("fp-fma-5")
}

///|
test "3509" {
  run_smt("3509")
}

///|
test "nl5" {
  run_smt("nl5")
}

///|
test "3146" {
  run_smt("3146")
}

///|
test "t103" {
  run_smt("t103")
}

///|
test "fp-to_ubv-5" {
  run_smt("fp-to_ubv-5")
}

///|
test "0xff" {
  run_smt("0xff")
}

///|
test "string-itos" {
  run_smt("string-itos")
}

///|
test "3279" {
  run_smt("3279")
}

///|
test "fp-le-ge" {
  run_smt("fp-le-ge")
}

///|
test "fp-pinf" {
  run_smt("fp-pinf")
}

///|
test "2939" {
  run_smt("2939")
}

///|
test "o3" {
  run_smt("o3")
}

///|
test "bad_patterns" {
  run_smt("bad_patterns")
}

///|
test "issue-1458" {
  run_smt("issue-1458")
}

///|
test "o7" {
  run_smt("o7")
}

///|
test "fp-to_fp_unsigned-2" {
  run_smt("fp-to_fp_unsigned-2")
}

///|
test "fp-to_ieee_bv-2" {
  run_smt("fp-to_ieee_bv-2")
}

///|
test "6116-float" {
  run_smt("6116-float")
}

///|
test "5710" {
  run_smt("5710")
}

///|
test "fp-to_ubv-10" {
  run_smt("fp-to_ubv-10")
}

///|
test "fp-conversions-15" {
  run_smt("fp-conversions-15")
}

///|
test "3154" {
  run_smt("3154")
}

///|
test "3362" {
  run_smt("3362")
}

///|
test "3401" {
  run_smt("3401")
}

///|
test "fp-to_ubv-7" {
  run_smt("fp-to_ubv-7")
}

///|
test "3244" {
  run_smt("3244")
}

///|
test "nl14" {
  run_smt("nl14")
}

///|
test "t14" {
  run_smt("t14")
}

///|
test "3397" {
  run_smt("3397")
}

///|
test "fp-uf-6" {
  run_smt("fp-uf-6")
}

///|
test "6117-5" {
  run_smt("6117-5")
}

///|
test "3264" {
  run_smt("3264")
}

///|
test "intervalDownDivide" {
  run_smt("intervalDownDivide")
}

///|
test "3175" {
  run_smt("3175")
}

///|
test "fp-to_fp_unsigned-7" {
  run_smt("fp-to_fp_unsigned-7")
}

///|
test "fp-fma-7" {
  run_smt("fp-fma-7")
}

///|
test "3527" {
  run_smt("3527")
}

///|
test "t182" {
  run_smt("t182")
}

///|
test "2549" {
  run_smt("2549")
}

///|
test "3299" {
  run_smt("3299")
}

///|
test "6079-9" {
  run_smt("6079-9")
}

///|
test "elim-uncnstr-tactic" {
  run_smt("elim-uncnstr-tactic")
}

///|
test "fp-to_ubv-23" {
  run_smt("fp-to_ubv-23")
}

///|
test "3929" {
  run_smt("3929")
}

///|
test "t170" {
  run_smt("t170")
}

///|
test "nl22" {
  run_smt("nl22")
}

///|
test "issue-1608" {
  run_smt("issue-1608")
}

///|
test "3738" {
  run_smt("3738")
}

///|
test "2431" {
  run_smt("2431")
}

///|
test "3597" {
  run_smt("3597")
}

///|
test "3554" {
  run_smt("3554")
}

///|
test "3378" {
  run_smt("3378")
}

///|
test "fp-to_fp_simplifier" {
  run_smt("fp-to_fp_simplifier")
}

///|
test "fp-to_ubv-29" {
  run_smt("fp-to_ubv-29")
}

///|
test "3620" {
  run_smt("3620")
}

///|
test "t177" {
  run_smt("t177")
}

///|
test "fp-to_ubv-31" {
  run_smt("fp-to_ubv-31")
}

///|
test "fp-rem-6" {
  run_smt("fp-rem-6")
}

///|
test "3862" {
  run_smt("3862")
}

///|
test "fp-eq-1" {
  run_smt("fp-eq-1")
}

///|
test "issue-1681" {
  run_smt("issue-1681")
}

///|
test "3713" {
  run_smt("3713")
}

///|
test "coercions" {
  run_smt("coercions")
}

///|
test "3891" {
  run_smt("3891")
}

///|
test "3985" {
  run_smt("3985")
}

///|
test "3982" {
  run_smt("3982")
}

///|
test "fp-template" {
  run_smt("fp-template")
}

///|
test "fp-model_evaluator_8" {
  run_smt("fp-model_evaluator_8")
}
