///|
test "2557" {
  run_smt("2557")
}

///|
test "t130" {
  run_smt("t130")
}

///|
test "3103" {
  run_smt("3103")
}

///|
test "t111" {
  run_smt("t111")
}

///|
test "fp-rem-5" {
  run_smt("fp-rem-5")
}

///|
test "mul" {
  run_smt("mul")
}

///|
test "2546" {
  run_smt("2546")
}

///|
test "z3.27" {
  run_smt("z3.27")
}

///|
test "mut_rec4sdk_output1" {
  run_smt("mut_rec4sdk_output1")
}

///|
test "3670" {
  run_smt("3670")
}

///|
test "4000" {
  run_smt("4000")
}

///|
test "intervalUpDivide" {
  run_smt("intervalUpDivide")
}
